import { useMutation } from "@tanstack/react-query";
import { useState } from "react";
import { ShieldCheck, RefreshCw } from "lucide-react";
import { checkedCompositionReview, compositionApi, type CompositionPending, type CompositionReview, type CompositionReviewRequest, compositionJobId, compositionPack, FILE_ACCESS_PACK, RECEIVER_PACK, type CompositionPack } from "../lib/composition";
import { Button, DataList, ErrorState, Field } from "./Primitives";

export const compositionLimitLabels: Record<string, string> = {
  max_attempts: "Fresh attempts", max_nodes_per_attempt: "Nodes per attempt", max_edges_per_attempt: "Edges per attempt", max_business_steps: "Cumulative business steps",
  max_generated_bytes: "Cumulative generated bytes", max_network_bytes: "Cumulative network bytes", max_peak_workspace_bytes: "Peak workspace bytes", max_workspace_files: "Workspace files",
  max_retained_metadata_bytes: "Metadata admission estimate (bytes)", max_reserved_attempt_ms: "Cumulative reserved time (ms)", per_attempt_wall_ms: "Attempt wall time (ms)", cleanup_reserve_ms: "Cleanup reserve per attempt (ms)",
};
export function CompositionCapabilities({ review }: { review: Pick<CompositionReview, "schema_version" | "pack" | "snapshot" | "environment" | "limits" | "objective"> }) {
  const fileAccess = compositionPack(review) === FILE_ACCESS_PACK;
  return <div className="composition-scope">
    <DataList items={fileAccess ? [
      { label: "Runner", value: review.environment.runner_id }, { label: "Control", value: "Retained file access" },
      { label: "Resource generation", value: String(review.environment.resource_generation ?? "Not reported") },
      { label: "Data", value: "Same retained generated records" },
      { label: "Success condition", value: "A fresh non-owner open is permission denied; the owner reads all unchanged records; worker requests close and attempt artifacts are cleaned." },
    ] : [
      { label: "Runner", value: review.environment.runner_id }, { label: "Retained policy", value: String(review.environment.policy_id) },
      { label: "Destination", value: `Loopback port ${String(review.environment.port)}` }, { label: "Data", value: "Fresh public synthetic JSONL" },
      { label: "Success condition", value: `All ${String(review.objective.predicate.record_count)} records delivered redacted; policy unchanged; native and receiver cleanup verified.` },
    ]} />
    <div className="composition-table" role="region" aria-label="Authorized methods" tabIndex={0}><table><caption>Installed capabilities and finite parameter domains</caption><thead><tr><th>Version-bound method</th><th>Parameters</th><th>Capabilities and effects</th><th>Implementation</th></tr></thead><tbody>{review.snapshot.methods.map(method => <tr key={method.behavior_id}><th scope="row">{method.behavior.title}<small>{method.action_id}</small></th><td>{Object.entries(method.parameter_domains).map(([key, values]) => <div key={key}>{key}: {values.map(value => JSON.stringify(value)).join(", ")}</div>)}{!Object.keys(method.parameter_domains).length ? "No variable parameters" : null}</td><td>{method.action.capabilities.join(", ")}<small>Safety tier: {method.action.safety_tier}</small><small>Reads: {Array.isArray(method.cost.reads) ? method.cost.reads.join(", ") || "none" : "not reported"}</small><small>Writes: {Array.isArray(method.cost.writes) ? method.cost.writes.join(", ") || "none" : "not reported"}</small>{method.cost.removes ? <small>Removes: {String(method.cost.removes)}</small> : null}</td><td><code>{method.implementation_digest}</code></td></tr>)}</tbody></table></div>
    <dl className="composition-limits">{Object.entries(review.limits).map(([key, value]) => <div key={key}><dt>{compositionLimitLabels[key] ?? key}</dt><dd>{value.toLocaleString()}</dd></div>)}</dl>
    <p>Reservations are charged before effects. Metadata bytes are an admission estimate, not a total-storage hard cap. Cleanup remains receipt-scoped after business authority ends.</p>
    <details><summary>Exact environment binding</summary><DataList items={Object.entries(review.environment).map(([key, value]) => ({ label: key.replaceAll("_", " "), value: <code>{String(value)}</code> }))} /></details>
  </div>;
}

export function CompositionSetup({ control, disabled, onSubmit, initialRequest, pack = RECEIVER_PACK }: { control: string; disabled: boolean; onSubmit: (pending: CompositionPending) => void; initialRequest?: CompositionReviewRequest; pack?: CompositionPack }) {
  const [question, setQuestion] = useState(initialRequest?.question ?? "");
  const [limits, setLimits] = useState<Record<string, number> | null>(initialRequest?.limits ?? null);
  const [actor, setActor] = useState("");
  const [acknowledged, setAcknowledged] = useState(false);
  const [reviewedRequest, setReviewedRequest] = useState<CompositionReviewRequest>();
  const review = useMutation({ mutationFn: async (body: CompositionReviewRequest) => checkedCompositionReview(await compositionApi.review(body), body), onSuccess: (_, body) => { setReviewedRequest(body); setAcknowledged(false); } });
  const reset = () => { review.reset(); setReviewedRequest(undefined); setAcknowledged(false); };
  return <section className="composition-section" aria-label="New composition objective">
    <h2>New objective</h2>
    <form onSubmit={event => { event.preventDefault(); setAcknowledged(false); const body = { control_owner_id: control, question: question.trim(), limits }; review.mutate(pack === FILE_ACCESS_PACK ? { ...body, schema_version: "bluefire.composition-review-request.v2", pack: FILE_ACCESS_PACK } : body); }}>
      <Field label="Objective question"><textarea value={question} maxLength={2000} rows={3} required disabled={disabled || review.isPending} onChange={event => { setQuestion(event.target.value); reset(); }} placeholder={pack === FILE_ACCESS_PACK ? "Does the retained control prevent a fresh non-owner read while preserving owner access?" : "What should this retained policy permit while preserving the records?"} /></Field>
      {limits ? <details><summary>Requested limits</summary><div className="composition-budget-inputs">{Object.entries(limits).map(([key, value]) => <Field label={compositionLimitLabels[key] ?? key} key={key}><input type="number" min={key === "max_edges_per_attempt" ? 0 : 1} step={1} required disabled={disabled || review.isPending} value={value} onChange={event => { setLimits({ ...limits, [key]: Number(event.target.value) }); reset(); }} /></Field>)}</div></details> : null}
      <Button type="submit" disabled={disabled || review.isPending || !question.trim()}><RefreshCw />{review.isPending ? "Checking capabilities" : "Review finite delegation"}</Button>
    </form>
    {review.error ? <ErrorState error={review.error} /> : null}
    {review.data && reviewedRequest ? <>
      <CompositionCapabilities review={review.data} />
      <p>This grant expires 15 minutes after issue. It permits new graphs only within these methods, parameters, environment bindings and cumulative limits. It does not authorize new tools or targets.</p>
      <Button size="small" onClick={() => { setLimits({ ...review.data!.limits }); reset(); }}>Adjust requested limits</Button>
      <Field label="Delegation reviewed by"><input value={actor} maxLength={128} autoComplete="off" disabled={disabled} onChange={event => setActor(event.target.value)} /></Field>
      <label className="check-row"><input type="checkbox" checked={acknowledged} disabled={disabled} onChange={event => setAcknowledged(event.target.checked)} /><span>I authorize the reviewed finite capabilities, data effects, cleanup reserve and cumulative budgets for this objective.</span></label>
      <Button variant="primary" disabled={disabled || !acknowledged || !actor.trim()} onClick={() => { const submission_id = crypto.randomUUID(); const id = compositionJobId(submission_id); onSubmit({ kind: "grant", id, owner: id, control, body: { submission_id, review: reviewedRequest, reviewed_by: actor.trim(), review_digest: review.data!.review_digest } }); }}><ShieldCheck />Issue capability grant</Button>
    </> : null}
  </section>;
}
