import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Bot, CheckCircle2, Scale, ShieldCheck, XCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { api } from "../lib/api";
import type { AIProposalDecisionResult, AIProposalReview, RunJob } from "../types";
import { Badge, Button, Callout, DataList, Field, LoadingState, Panel, PanelHeader, formatDate, sentence } from "./Primitives";

export function ProposalReviewWorkspace({ job, onDecision, onReviewLoaded }: { job: RunJob; onDecision?: (result: AIProposalDecisionResult, review: AIProposalReview) => void; onReviewLoaded?: (review: AIProposalReview) => void }) {
  const client = useQueryClient();
  const listQuery = useQuery({ queryKey: ["job-proposals", job.job_id], queryFn: () => api.proposalReviews(job.job_id), refetchInterval: job.state === "awaiting_approval" ? 1000 : false });
  const requestedId = typeof job.progress.proposal_record_id === "string" ? job.progress.proposal_record_id : undefined;
  const [selectedId, setSelectedId] = useState<string>(); const [confirmed, setConfirmed] = useState(false); const [decidedBy, setDecidedBy] = useState("");
  const resolvedId = selectedId ?? requestedId ?? listQuery.data?.proposals.at(-1)?.proposal_record_id;
  const detailQuery = useQuery({ queryKey: ["job-proposal", job.job_id, resolvedId], queryFn: () => api.proposalReview(job.job_id, resolvedId!), enabled: Boolean(resolvedId) });
  useEffect(() => { setSelectedId(undefined); setConfirmed(false); setDecidedBy(""); }, [job.job_id]);
  useEffect(() => { setConfirmed(false); setDecidedBy(""); }, [resolvedId]);
  useEffect(() => { if (detailQuery.data) onReviewLoaded?.(detailQuery.data); }, [detailQuery.data, onReviewLoaded]);
  const decisionMutation = useMutation({ mutationFn: (decision: "accept" | "reject") => api.decideProposal(job.job_id, detailQuery.data!, decidedBy, decision), onSuccess: (result) => { setConfirmed(false); setDecidedBy(""); client.invalidateQueries({ queryKey: ["job-proposals", job.job_id] }); client.invalidateQueries({ queryKey: ["job-proposal", job.job_id] }); onDecision?.(result, result.proposal); } });
  if (listQuery.isPending) return <LoadingState label="Loading durable proposal reviews" />;
  if (listQuery.isError) return <Callout tone="danger" title="Proposal reviews unavailable">{listQuery.error.message}</Callout>;
  const proposals = listQuery.data.proposals;
  if (!proposals.length) return <Panel><PanelHeader eyebrow="Durable AI review" title="No proposal gate for this job"/><Callout title="Deterministic or completed path">Proposal review records appear only when Assist or review-required Auto pauses before a registered next-node choice.</Callout></Panel>;
  const review = detailQuery.data ?? proposals.find((item) => item.proposal_record_id === resolvedId);
  const proposal = review?.record.proposal;
  const isCurrentGate = job.state === "awaiting_approval" && job.progress.approval_kind === "ai_proposal" && requestedId === review?.proposal_record_id;
  const decisionReady = Boolean(review && review.status === "pending" && isCurrentGate && confirmed && decidedBy.trim());
  return <Panel className="proposal-review"><PanelHeader eyebrow="Durable AI review" title="Bounded runtime proposal" detail="Only the observed registered transition, compatible contract fields, exact-profile actions, or one eligible retry can be proposed; deterministic policy still decides what is valid." actions={<Badge tone={review?.status === "pending" ? "warning" : review?.status === "accepted" ? "success" : "neutral"}>{sentence(review?.status ?? "loading")}</Badge>}/>
    <div className="proposal-boundaries" aria-label="AI decision boundaries"><article><Bot/><strong>Proposal</strong><small>One allowlisted runtime choice</small></article><article><Scale/><strong>Policy</strong><small>Compatibility, scope, profile, tier, and retry checks</small></article><article><ShieldCheck/><strong>Execute approval</strong><small>Separate fresh one-time capability when effects are possible</small></article></div>
    {proposals.length > 1 ? <Field label="Proposal record"><select value={resolvedId} onChange={(event) => setSelectedId(event.target.value)}>{proposals.map((item) => <option key={item.proposal_record_id} value={item.proposal_record_id}>{item.proposal_record_id} · {item.status}</option>)}</select></Field> : null}
    {detailQuery.isPending ? <LoadingState label="Loading exact proposal envelope" /> : detailQuery.isError ? <Callout tone="danger" title="Exact proposal unavailable">{detailQuery.error.message}</Callout> : review && proposal ? <>
      <Callout tone={isCurrentGate ? "warning" : review.status === "accepted" ? "success" : "info"} title={isCurrentGate ? "Job is paused before the proposed node" : `Proposal is ${review.status}`}>{proposal.rationale || "No model rationale was retained."}</Callout>
      <DataList items={[{ label: "Proposal record", value: <code>{review.proposal_record_id}</code> }, { label: "Source run", value: <code>{review.source_run_id}</code> }, { label: "Proposal type", value: sentence(proposal.proposal_type) }, { label: "Selected step", value: proposal.selected_step_id ? <code>{proposal.selected_step_id}</code> : "None" }, { label: "Selected behavior", value: proposal.selected_behavior_id ? <code>{proposal.selected_behavior_id}</code> : "None" }, { label: "Registered action", value: proposal.selected_action_id ? <code>{proposal.selected_action_id}</code> : "None" }, { label: "Observed edge", value: proposal.selected_edge ? <code>{`${proposal.selected_edge.from_step} · ${proposal.selected_edge.outcome} → ${proposal.selected_edge.to_step}`}</code> : "No edge change" }, { label: "Typed parameter changes", value: proposal.parameter_changes?.length ? <code>{JSON.stringify(proposal.parameter_changes)}</code> : "None" }, { label: "Allowed steps", value: review.record.allowed_step_ids?.join(", ") || "Not reported" }, { label: "Allowed behaviors", value: review.record.allowed_behavior_ids?.join(", ") || "Not reported" }, { label: "Eligible retry steps", value: review.record.retryable_step_ids?.join(", ") || "None" }, { label: "Created", value: formatDate(review.created_at) }]} />
      <div className="proposal-digests"><code title="State digest">{review.state_digest}</code><code title="Plan digest">{review.plan_digest}</code><code title="Proposal digest">{review.proposal_digest}</code></div>
      {review.resolution ? <DataList items={[{ label: "Decision", value: sentence(String(review.resolution.decision ?? review.status)) }, { label: "Decided by", value: review.decided_by ?? "Not reported" }, { label: "Continuation", value: typeof review.resolution.continuation === "object" ? "Immutable lineage-linked continuation prepared" : "Original run retained" }]} /> : null}
      {review.status === "pending" ? <div className="proposal-controls"><label className="check-row"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} disabled={!isCurrentGate || decisionMutation.isPending}/><span><strong>I reviewed these exact three digests</strong><small>Unchecked by default; never persisted</small></span></label><Field label="Proposal reviewer identity"><input value={decidedBy} onChange={(event) => setDecidedBy(event.target.value)} disabled={!isCurrentGate || decisionMutation.isPending} autoComplete="off" maxLength={128}/></Field><div className="dialog-actions"><Button variant="danger" onClick={() => decisionMutation.mutate("reject")} disabled={!decisionReady || decisionMutation.isPending}><XCircle/>Reject and keep original run</Button><Button variant="primary" onClick={() => decisionMutation.mutate("accept")} disabled={!decisionReady || decisionMutation.isPending}><CheckCircle2/>Accept registered continuation</Button></div>{!isCurrentGate ? <p className="field-note"><AlertTriangle/>This record is not the job’s current proposal gate, so decisions are disabled.</p> : null}</div> : null}
      {decisionMutation.isError ? <Callout tone="danger" title="Proposal decision refused">{decisionMutation.error.message}</Callout> : null}
    </> : null}
  </Panel>;
}
