import { AlertTriangle } from "lucide-react";
import { Link } from "react-router-dom";
import { collectionObservationSteps, collectionObserverSelection, collectionSemanticsCollector } from "../lib/collection-observation";
import { configurationForMode, hasLocalExecuteReview } from "../lib/run-configuration";
import type { AutonomyLevel, CatalogResponse, PreflightReport, RunConfiguration, Scenario } from "../types";
import { Badge, Callout, DataList, Field, Panel, PanelHeader, sentence } from "./Primitives";

export function RunConfigurationPanel({ scenario, config, onChange, catalog, preflight }: { scenario: Scenario; config: RunConfiguration; onChange: (config: RunConfiguration) => void; catalog: CatalogResponse; preflight?: PreflightReport }) {
  const set = <K extends keyof RunConfiguration>(key: K, value: RunConfiguration[K]) => onChange({ ...config, [key]: value });
  const collectionSteps = collectionObservationSteps(scenario);
  const selectMode = (mode: RunConfiguration["mode"]) => onChange(configurationForMode(config, mode, catalog, scenario));
  const profiles = catalog.runner_profiles.filter((profile) => profile.mode === config.mode);
  const selectedProfile = profiles.find((profile) => profile.id === config.profileId);
  const providers = catalog.ai.providers ?? [{ provider_id: catalog.ai.active_provider ?? "deterministic-offline.v1", kind: "deterministic", model: "deterministic-planner.v1", health: { state: catalog.ai.provider_health ?? "not_reported" } }];
  const selectedProvider = providers.find((provider) => provider.provider_id === config.provider) ?? providers[0];
  const providerHealth = selectedProvider?.health?.state ?? catalog.ai.provider_health ?? "not_reported";
  return <Panel className="run-config"><PanelHeader eyebrow="Intent" title="Run configuration" detail="Choose effects and scope. Preflight checks the exact plan before a job can start." />
    <div className="config-body">
      <fieldset><legend>Effect mode</legend><div className="choice-grid two">{(["simulate", "execute"] as const).map((mode) => <label key={mode}><input type="radio" name="run-mode" checked={config.mode === mode} onChange={() => selectMode(mode)}/><span><strong>{sentence(mode)}</strong><small>{mode === "simulate" ? "Synthetic evidence only" : "Approved runner actions"}</small></span></label>)}</div></fieldset>
      <div className="config-grid primary-environment">
        <Field label="Runner profile"><select value={config.profileId} onChange={(event) => set("profileId", event.target.value)}><option value="">Select profile</option>{profiles.map((profile) => <option key={profile.id}>{profile.id}</option>)}</select></Field>
        <Field label="Target scope" hint="Only these exact scope references may be used."><input value={config.scopeRefs.join(", ")} onChange={(event) => set("scopeRefs", event.target.value.split(",").map((item) => item.trim()).filter(Boolean))}/></Field>
      </div>
      <fieldset><legend>AI autonomy</legend><div className="choice-grid three">{(["off", "assist", "auto"] as AutonomyLevel[]).map((level) => <label key={level}><input type="radio" name="autonomy" checked={config.autonomy === level} onChange={() => set("autonomy", level)}/><span><strong>{sentence(level)}</strong><small>{level === "off" ? "Deterministic" : level === "assist" ? "Review proposal" : "Policy-valid Simulate choices"}</small></span></label>)}</div><p className="field-note">Off uses deterministic planning. Assist asks you to review proposals. Auto may apply allowed Simulate choices; Execute always needs separate approval.</p></fieldset>
      <details className="provider-details"><summary>AI provider & environment details</summary>
        <div className="config-grid">
          <Field label="Provider"><select value={selectedProvider?.provider_id ?? config.provider} onChange={(event) => { const provider = providers.find((item) => item.provider_id === event.target.value); onChange({ ...config, provider: event.target.value, model: provider?.model ?? "", endpoint: "" }); }}>{providers.map((provider) => <option value={provider.provider_id} key={provider.provider_id}>{provider.provider_id}</option>)}</select></Field>
          <div className="health-field"><span>Provider health</span><Badge tone={providerHealth === "ready" || providerHealth === "healthy" ? "success" : "warning"} dot>{sentence(providerHealth)}</Badge></div>
        </div>
        <DataList items={[{ label: "Model", value: selectedProvider?.model ?? config.model }, { label: "Endpoint and credentials", value: <Link to="/ai-planner">Configure providers</Link> }, { label: "Selected runner", value: "The profile resolves the active local enrollment. Manage it from Runners." }, { label: "Safety authority", value: selectedProfile?.safety_tiers.map(sentence).join(", ") ?? "Select a profile" }]} />
        <p className="field-note">Provider settings are managed by the local service. AI Off uses deterministic planning regardless of the selected provider.</p>
      </details>
      <details><summary>Policy, approval & budgets</summary><Callout title="Profile-owned enforcement">These values come from the selected canonical profile and are bound into preflight. Unsupported browser overrides are intentionally not shown.</Callout><DataList items={[{ label: "Approval", value: selectedProfile ? selectedProfile.approval_required ? "Required for Execute" : "Not required by profile" : "Select a profile" }, { label: "Cleanup", value: selectedProfile ? sentence(selectedProfile.cleanup_policy) : "Select a profile" }, { label: "Maximum steps", value: selectedProfile?.budgets.max_steps ?? "Select a profile" }, { label: "Maximum seconds", value: selectedProfile?.budgets.max_seconds ?? "Select a profile" }, { label: "Maximum artifacts", value: selectedProfile?.budgets.max_artifacts ?? "Select a profile" }, { label: "Maximum bytes", value: selectedProfile?.budgets.max_bytes ? `${Math.round(selectedProfile.budgets.max_bytes / 1_048_576)} MiB` : "Select a profile" }, { label: "Counterfactuals", value: "Planner-derived and always labeled; no unsupported browser switch" }]} />

        {config.mode === "execute" && !hasLocalExecuteReview(preflight) ? <LocalExecuteReview config={config} onChange={onChange} preflight={preflight} /> : null}
      </details>
      <details open={collectionSteps.length > 0 ? true : undefined}><summary>Observation & detection</summary><Callout title="Canonical records only">Execute binds selected per-run collectors into preflight and approval. Runner output remains executed evidence; observed records must come from a declared collector. Detection Lab validation is managed separately.</Callout><div className="choice-grid two">{["collector.filesystem.sandbox.v1"].map((collector) => <label key={collector}><input type="checkbox" checked={config.collectors.includes(collector)} disabled/><span><strong>{collector}</strong><small>Required Execute collector for declared sandbox artifacts</small></span></label>)}</div>
        <label className="check-row"><input type="checkbox" checked={config.collectors.includes(collectionSemanticsCollector)} disabled={config.mode !== "execute"} onChange={(event) => set("collectors", collectionObserverSelection(config, event.target.checked))}/><span><strong>Collection contents (bounded synthetic records)</strong><small>Independently reads the staged file after each reviewed collection step, hashes the same bytes, and records retained/redacted counts without record values. Other action types are skipped.</small></span></label>{collectionSteps.length > 0 ? <DataList items={collectionSteps.map((step) => ({ label: `After ${step.stepId}`, value: step.path }))}/> : null}<p className="field-note">The server derives the exact path and schedule from the approved native collection method and parameters, including a signed package binding. A compatible replay uses its own approved output path. Missing contents observation leaves a compatible collection experiment incomplete.</p>
        <DataList items={[{ label: "Runner results", value: "Executed evidence, never observed" }, { label: "Independent observation", value: preflight?.collectors?.join(", ") || (config.mode === "execute" ? config.collectors.join(", ") : "Execute only") }, { label: "Unavailable collection", value: "Rejected before Execute or recorded as unknown evidence" }, { label: "Detection lifecycle", value: "Managed in Detection Lab from canonical evidence" }, { label: "Fixture mode", value: "Defined by the chosen scenario, not a browser preference" }]} /></details>
    </div>
  </Panel>;
}

export function LocalExecuteReview({ config, onChange, preflight }: { config: RunConfiguration; onChange: (config: RunConfiguration) => void; preflight?: PreflightReport }) {
  const set = <K extends keyof RunConfiguration>(key: K, value: RunConfiguration[K]) => onChange({ ...config, [key]: value });
  const approvalBinding = preflight?.approval_binding;
  const approvalEnvelope = preflight?.approval_envelope;
  const approvalReviewReady = hasLocalExecuteReview(preflight);
  return <section className="run-local-review" aria-label="Prepare Execute request">{config.mode === "execute" ? <div className="approval-box"><AlertTriangle/><div><strong>Review before durable job creation</strong><p>Review the canonical primary and alternate contracts and acknowledge the exact digests below. This browser acknowledgement is never sent as an execution capability; the durable job requires a new unchecked, job-bound approval after it is created.</p>{approvalReviewReady && approvalBinding && approvalEnvelope ? <div className="approval-binding-summary" aria-label="Execute approval binding"><DataList items={[{ label: "State digest", value: <code>{approvalBinding.state_digest}</code> }, { label: "Plan digest", value: <code>{approvalBinding.plan_digest}</code> }, { label: "Target scope digest", value: <code>{approvalBinding.target_scope_digest}</code> }, { label: "Envelope digest", value: <code>{approvalEnvelope.envelope_digest}</code> }, { label: "Profile / maximum tier", value: `${approvalBinding.profile_id} / ${sentence(approvalBinding.maximum_tier)}` }]} /></div> : <p className="approval-pending">Run preflight first. Job creation stays disabled until the canonical plan, exact scope, and complete approval envelope are displayed.</p>}<label className="check-row"><input type="checkbox" checked={config.approved} disabled={!approvalReviewReady} onChange={(event) => set("approved", event.target.checked)}/><span><strong>I reviewed this exact displayed Execute envelope</strong><small>Local acknowledgement only; cleared after preflight, intent changes, reload, and job submission</small></span></label><Field label="Prepared operator label" hint="Local preparation only. The durable job approval will request identity again."><input value={config.approvedBy} disabled={!approvalReviewReady} onChange={(event) => set("approvedBy", event.target.value)} autoComplete="off" placeholder="Operator label" required={config.mode === "execute"}/></Field></div></div> : null}</section>;
}
