import { Link } from "react-router-dom";
import { collectionObservationSteps, collectionObserverSelection, collectionSemanticsCollector } from "../lib/collection-observation";
import { configurationForMode } from "../lib/run-configuration";
import { collectorLabel, profileLabel, scopeLabel } from "../lib/run-review-labels";
import type { AutonomyLevel, CatalogResponse, PreflightReport, RunConfiguration, Scenario } from "../types";
import { Badge, Callout, DataList, Field, Panel, PanelHeader, sentence } from "./Primitives";

export function RunConfigurationPanel({ scenario, config, onChange, catalog, preflight, assistedSetup = false, runtimeLockedOff = false }: { runtimeLockedOff?: boolean; assistedSetup?: boolean; scenario: Scenario; config: RunConfiguration; onChange: (config: RunConfiguration) => void; catalog: CatalogResponse; preflight?: PreflightReport }) {
  const set = <K extends keyof RunConfiguration>(key: K, value: RunConfiguration[K]) => onChange({ ...config, [key]: value });
  const collectionSteps = collectionObservationSteps(scenario);
  const selectMode = (mode: RunConfiguration["mode"]) => onChange(configurationForMode(config, mode, catalog, scenario));
  const profiles = catalog.runner_profiles.filter((profile) => profile.mode === config.mode);
  const selectedProfile = profiles.find((profile) => profile.id === config.profileId);
  const availableScope = [...new Set([...(selectedProfile?.scope ?? []), ...config.scopeRefs])];
  const providers = catalog.ai.providers ?? [{ provider_id: catalog.ai.active_provider ?? "deterministic-offline.v1", kind: "deterministic", model: "deterministic-planner.v1", health: { state: catalog.ai.provider_health ?? "not_reported" } }];
  const selectedProvider = providers.find((provider) => provider.provider_id === config.provider);
  const providerHealth = selectedProvider?.health?.state ?? "not_selected";
  return <Panel className="run-config"><PanelHeader title="Run setup" detail="Choose the environment and requested access, then check the plan." />
    <div className="config-body">
      <fieldset><legend>Effect mode</legend><div className="choice-grid two">{(["simulate", "execute"] as const).map((mode) => <label key={mode}><input type="radio" name="run-mode" checked={config.mode === mode} onChange={() => selectMode(mode)}/><span><strong>{sentence(mode)}</strong><small>{mode === "simulate" ? "Synthetic evidence only" : "Approved runner actions"}</small></span></label>)}</div></fieldset>
      <div className="primary-environment">
        <Field label="Environment profile"><select value={config.profileId} onChange={(event) => set("profileId", event.target.value)}><option value="">Select environment profile</option>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profileLabel(profile.id)} · {profile.platforms.map(sentence).join(" / ")}</option>)}</select></Field>
        {selectedProfile ? <p className="field-note">{sentence(selectedProfile.environment_type)} · {selectedProfile.enabled_actions.length} enabled methods · {selectedProfile.budgets.max_seconds ?? "Unspecified"} seconds maximum</p> : <p>Select a compatible environment profile before checking the plan.</p>}
        <fieldset><legend>Requested access</legend>{availableScope.length ? availableScope.map(reference => <label className="check-row" key={reference}><input type="checkbox" checked={config.scopeRefs.includes(reference)} onChange={event => set("scopeRefs", event.target.checked ? [...config.scopeRefs, reference] : config.scopeRefs.filter(item => item !== reference))}/><span><strong>{scopeLabel(reference)}</strong>{!selectedProfile?.scope.includes(reference) ? <small>Not listed by this profile; preflight must verify this request.</small> : null}</span></label>) : <p>No access selected.</p>}<p className="field-note">Selecting a profile does not add access. The service checks these requests against its configured permissions.</p></fieldset>
        <details><summary>Environment and scope references</summary><DataList items={[{ label: "Profile ID", value: <code>{config.profileId || "Not selected"}</code> }, { label: "Profile permits", value: selectedProfile?.scope.join(", ") ?? "Not selected" }]} /><Field label="Target scope" hint="Advanced: exact references to already configured scopes. Adding a reference does not grant permission."><input value={config.scopeRefs.join(", ")} onChange={(event) => set("scopeRefs", event.target.value.split(",").map((item) => item.trim()).filter(Boolean))}/></Field></details>
      </div>
      <fieldset disabled={runtimeLockedOff}><legend>{assistedSetup ? "AI during the run" : "AI autonomy"}</legend><div className="choice-grid three">{(["off", "assist", "auto"] as AutonomyLevel[]).map((level) => <label key={level}><input type="radio" name="autonomy" checked={config.autonomy === level} onChange={() => set("autonomy", level)}/><span><strong>{sentence(level)}</strong><small>{level === "off" ? "Deterministic" : level === "assist" ? "Review proposal" : scenario.adaptive_execution ? "Reviewed method choices" : "Policy-valid Simulate choices"}</small></span></label>)}</div><p className="field-note">{runtimeLockedOff ? "Runtime AI stays Off so each receiver phase runs the reviewed experiment without model-driven changes." : scenario.adaptive_execution ? "Off follows saved steps. Assist asks you to review a change. Auto may choose one reviewed alternative after an eligible result and continue within the original Execute approval. A new target, method, parameter or wider effect requires a new decision." : assistedSetup ? "These settings control planning inside the run. The Assistant has its own mode and provider for preparing the experiment and reviewing evidence." : "Off uses deterministic planning. Assist asks you to review proposals. Auto may apply allowed Simulate choices; Execute always needs separate approval."}</p></fieldset>
      <details className="provider-details"><summary>AI provider & environment details</summary>
        <div className="config-grid">
          <Field label={assistedSetup ? "Runtime provider" : "Provider"} hint={!selectedProvider ? "Choose a configured provider before enabling runtime AI. Off makes no model requests." : undefined}><select disabled={runtimeLockedOff} value={selectedProvider?.provider_id ?? ""} onChange={(event) => { const provider = providers.find((item) => item.provider_id === event.target.value); onChange({ ...config, provider: event.target.value, model: provider?.model ?? "", endpoint: "" }); }}><option value="" disabled>Choose a configured provider</option>{providers.map((provider) => <option value={provider.provider_id} key={provider.provider_id}>{provider.provider_id}</option>)}</select></Field>
          <div className="health-field"><span>Provider health</span><Badge tone={providerHealth === "ready" || providerHealth === "healthy" ? "success" : "warning"} dot>{sentence(providerHealth)}</Badge></div>
        </div>
        <DataList items={[{ label: "Model", value: selectedProvider?.model ?? "No configured provider selected" }, { label: "Endpoint and credentials", value: <Link to="/settings#model-connection">Configure providers</Link> }, { label: "Selected runner", value: "The profile resolves the active local enrollment. Manage it from Runners." }, { label: "Safety authority", value: selectedProfile?.safety_tiers.map(sentence).join(", ") ?? "Select a profile" }]} />
        <p className="field-note">Provider settings are managed by the local service. AI Off uses deterministic planning regardless of the selected provider.</p>
      </details>
      <details><summary>Policy, approval & budgets</summary><Callout title="Profile-owned enforcement">These values come from the selected canonical profile and are bound into preflight. Unsupported browser overrides are intentionally not shown.</Callout><DataList items={[{ label: "Approval", value: selectedProfile ? selectedProfile.approval_required ? "Required for Execute" : "Not required by profile" : "Select a profile" }, { label: "Cleanup", value: selectedProfile ? sentence(selectedProfile.cleanup_policy) : "Select a profile" }, { label: "Maximum steps", value: selectedProfile?.budgets.max_steps ?? "Select a profile" }, { label: "Maximum seconds", value: selectedProfile?.budgets.max_seconds ?? "Select a profile" }, { label: "Maximum artifacts", value: selectedProfile?.budgets.max_artifacts ?? "Select a profile" }, { label: "Maximum bytes", value: selectedProfile?.budgets.max_bytes ? `${Math.round(selectedProfile.budgets.max_bytes / 1_048_576)} MiB` : "Select a profile" }, { label: "Counterfactuals", value: "Planner-derived and always labeled; no unsupported browser switch" }]} />

      </details>
      <section className="run-observations" aria-label="Required observations"><h3>Observations</h3>
        {config.mode === "execute" ? <><p><strong>Created files and cleanup · Required</strong></p><p>Independently checks the files this run creates and whether cleanup removes them.</p>{!config.collectors.includes("collector.filesystem.sandbox.v1") ? <p role="alert">The required file observer is missing from this request. Select a compatible configuration before preflight.</p> : null}</> : <p>Simulate produces synthetic records. Independent file observations are available during Execute.</p>}
        <label className="check-row"><input type="checkbox" checked={config.collectors.includes(collectionSemanticsCollector)} disabled={config.mode !== "execute"} onChange={(event) => set("collectors", collectionObserverSelection(config, event.target.checked))}/><span><strong>Collection contents and redaction</strong><small>Count retained and redacted records in the reviewed output. Record values are excluded.</small></span></label>
        {collectionSteps.length > 0 ? <><p>Needed to assess the selected collection methods.</p><DataList items={collectionSteps.map((step) => ({ label: "Collection output", value: step.path }))}/></> : null}
        <details><summary>Observation details</summary><DataList items={[{ label: "Selected observers", value: (preflight?.collectors ?? (config.mode === "execute" ? config.collectors : [])).map(collectorLabel).join(", ") || "Execute only" }, { label: "Observer references", value: config.collectors.join(", ") }, { label: "Evidence meaning", value: "Runner results record execution. Independent observers record measured changes." }]} /><p>The service derives observation paths from the reviewed method and parameters. Missing observations remain unknown; they do not count as a successful detection.</p></details>
      </section>
    </div>
  </Panel>;
}
