import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import * as Tooltip from "@radix-ui/react-tooltip";
import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "react-router-dom";
import { expect, it, vi } from "vitest";
import { api } from "../src/lib/api";
import { demoCatalog, demoScenario } from "../src/lib/demo";
import { BuilderPage } from "../src/pages/Builder";
import { ProductProvider } from "../src/state/ProductContext";
import { AssistanceProvider, useAssistanceSelection } from "../src/state/AssistanceContext";
import { ExperimentAssistant } from "../src/components/ExperimentAssistant";
import { graphDocument } from "../src/lib/graph-assistance";
import type { AssistanceContext, GraphSelection } from "../src/lib/assistance";
function Selection() { return <output aria-label="Published selection">{JSON.stringify(useAssistanceSelection())}</output>; }
const digest = `sha256:${"a".repeat(64)}`;
const context = (selection: GraphSelection): AssistanceContext => ({ schema_version: "bluefire.assistance-context.v1", context_digest: digest, selected: selection,
  capabilities: [{ id: "graph.propose_and_validate", title: "Edit selected step", available: true, supported_autonomy: ["assist", "auto"], reason: "Review parameters", native_path: "/builder" }], limitations: ["No execution"] });
it("publishes selected step and dirty graph while keeping new experiments explicit", async () => {
  localStorage.setItem("bluefire.local.scenario.v1", JSON.stringify(demoScenario));
  localStorage.setItem("bluefire.local.scenario-saved.v1", JSON.stringify(demoScenario));
  const client = new QueryClient({ defaultOptions: { queries: { retry: false, staleTime: Infinity } } }); client.setQueryData(["catalog"], demoCatalog);
  vi.spyOn(api, "assistanceGraphContext").mockImplementation(async base => context({ kind: "graph", base_scenario: base }));
  const editContext = vi.spyOn(api, "assistanceGraphEditContext").mockImplementation(async selection => context(selection));
  const submit = vi.spyOn(api, "submitAssistance");
  const app = <QueryClientProvider client={client}><Tooltip.Provider><MemoryRouter><ProductProvider><AssistanceProvider><BuilderPage/><Selection/><ExperimentAssistant providers={[]}/></AssistanceProvider></ProductProvider></MemoryRouter></Tooltip.Provider></QueryClientProvider>;
  const first = render(app);
  await userEvent.click(await screen.findByRole("button", { name: "Steps" }));
  const step = demoScenario.steps[0]!; const label = demoCatalog.behaviors.find(behavior => behavior.id === step.behavior_id)!.title;
  await userEvent.click(within(screen.getByRole("list", { name: "Experiment steps" })).getByRole("button", { name: new RegExp(`^1 ${label}`) }));
  await userEvent.click(screen.getByRole("button", { name: "Plan with Assistant" }));
  await waitFor(() => expect(editContext).toHaveBeenCalled());
  expect(JSON.parse(screen.getByLabelText("Published selection").textContent!).editStep).toEqual({ scenario: graphDocument(demoScenario), step_id: step.id, dirty: false });
  expect(within(screen.getByRole("region", { name: "Current selection" })).getByText("Edit the selected step")).toBeVisible();
  const name = screen.getByRole("textbox", { name: "Experiment name" });
  await userEvent.clear(name);
  expect(name).toHaveValue("");
  expect(within(screen.getByRole("region", { name: "Current selection" })).getByText(/Complete the current graph fields/)).toBeVisible();
  expect(screen.getByRole("button", { name: "Start work" })).toBeDisabled();
  expect(within(screen.getByRole("region", { name: "Current selection" })).getByText("Edit the selected step")).toBeVisible();
  await userEvent.type(name, `${demoScenario.title} changed`);
  await waitFor(() => expect(editContext.mock.lastCall?.[0].edit_step?.scenario.title).toBe(`${demoScenario.title} changed`));
  expect(editContext.mock.lastCall?.[0].edit_step?.dirty).toBe(true);
  await userEvent.selectOptions(screen.getByRole("combobox", { name: "Assistant operation" }), "new");
  expect(within(screen.getByRole("region", { name: "Current selection" })).getByText("New experiment", { selector: "strong" })).toBeVisible();
  expect(submit).not.toHaveBeenCalled();
  const editCalls = editContext.mock.calls.length;
  first.unmount(); render(app);
  expect(await screen.findByRole("combobox", { name: "Assistant operation" })).toHaveValue("new");
  expect(editContext.mock.calls.length).toBe(editCalls);
  expect(submit).not.toHaveBeenCalled();
});
