import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, Bot, Braces, CheckCircle2, KeyRound, LockKeyhole, Power, Route, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ProposalReviewWorkspace } from "../components/ProposalReview";
import { api } from "../lib/api";
import { useProduct } from "../state/ProductContext";
import type { AIGraphDraftResult, AIProposalDecisionResult, AIProposalReview, AutonomyLevel, Behavior, Scenario } from "../types";
import { Badge, Button, Callout, DataList, ErrorState, Field, LoadingState, PageHeader, Panel, PanelHeader, sentence } from "../components/Primitives";

export function AIPlannerPage() {
  const query = useQuery({ queryKey: ["catalog"], queryFn: api.catalog });
  const providerResources = useQuery({ queryKey: ["resources", "model-providers"], queryFn: () => api.resources("model-providers") });
  const { scenario, setScenario, runConfig, setRunConfig, activeRun } = useProduct(); const [objective, setObjective] = useState(scenario.purpose); const [notice, setNotice] = useState<string>(); const navigate = useNavigate(); const client = useQueryClient();
  const [providerId, setProviderId] = useState("deterministic.local-review.v1"); const [providerModel, setProviderModel] = useState("deterministic-planner.v1"); const [reviewJobId, setReviewJobId] = useState(""); const [draftResult, setDraftResult] = useState<AIGraphDraftResult>(); const [freshApproval, setFreshApproval] = useState<Record<string, unknown>>(); const [acceptedReview, setAcceptedReview] = useState<AIProposalReview>(); const [approvalConfirmed, setApprovalConfirmed] = useState(false); const [approvalOperator, setApprovalOperator] = useState("");
  const jobQuery = useQuery({ queryKey: ["job", "planner-review", reviewJobId], queryFn: () => api.job(reviewJobId), enabled: Boolean(reviewJobId) });
  const saveProvider = useMutation({ mutationFn: () => api.saveResource("model-providers", providerId, { id: providerId, kind: "deterministic", model: providerModel, timeout_seconds: 1, max_retries: 0, max_output_tokens: 800, redaction: { enabled: true, redact_keys: ["api_key", "authorization", "cookie", "credential", "password", "secret", "token"], max_string_chars: 4000, include_evidence_content: false } }, "draft"), onSuccess: ({ resource }) => { setNotice(`${resource.id} saved as a secret-free deterministic provider draft.`); client.invalidateQueries({ queryKey: ["resources", "model-providers"] }); }, onError: (error) => setNotice(error instanceof Error ? error.message : "The provider draft was refused.") });
  const lifecycle = useMutation({ mutationFn: ({ id, action }: { id: string; action: "activate" | "deactivate" }) => action === "activate" ? api.activateResource("model-providers", id) : api.deactivateResource("model-providers", id), onSuccess: ({ resource }) => { setNotice(`${resource.id} is now ${resource.status}. Provider selection was refreshed by the control plane.`); client.invalidateQueries({ queryKey: ["resources", "model-providers"] }); client.invalidateQueries({ queryKey: ["catalog"] }); }, onError: (error) => setNotice(error instanceof Error ? error.message : "The provider lifecycle action was refused.") });
  const serverDraft = useMutation({ mutationFn: () => api.aiDraft(objective.trim(), runConfig.provider || null, 8, 16), onSuccess: (result) => { setDraftResult(result); setNotice(`${result.draft_id} returned as an unsaved registered-contract draft. Nothing was saved or authorized.`); }, onError: (error) => setNotice(error instanceof Error ? error.message : "The control-plane draft was refused.") });
  const approveContinuation = useMutation({ mutationFn: () => api.approveJob(reviewJobId, approvalOperator.trim()), onSuccess: (result) => { client.setQueryData(["job", "planner-review", reviewJobId], result.job); setFreshApproval(undefined); setApprovalConfirmed(false); setApprovalOperator(""); setNotice(`The fresh proposal-continuation envelope for ${result.job.job_id} was approved once and released.`); }, onError: (error) => setNotice(error instanceof Error ? error.message : "The fresh Execute approval was refused."), onSettled: () => { setApprovalConfirmed(false); setApprovalOperator(""); } });
  useEffect(() => { setFreshApproval(undefined); setAcceptedReview(undefined); setApprovalConfirmed(false); setApprovalOperator(""); }, [reviewJobId]);
  if (query.isPending) return <LoadingState label="Loading AI planner configuration" />;
  if (query.isError) return <ErrorState error={query.error} retry={() => query.refetch()} />;
  const setAutonomy = (autonomy: AutonomyLevel) => setRunConfig({ ...runConfig, autonomy });
  const providers = query.data.ai.providers ?? [{ provider_id: query.data.ai.active_provider ?? "deterministic-offline.v1", kind: "deterministic", model: "deterministic-planner.v1", credential_reference: null, health: { state: query.data.ai.provider_health ?? "not_reported", message: "Legacy catalog health" } }];
  const selectedProvider = providers.find((provider) => provider.provider_id === runConfig.provider) ?? providers[0]; const providerHealth = selectedProvider?.health?.state ?? "not_reported";
  const offlineDraft = () => { const words = new Set(objective.toLowerCase().split(/\W+/)); const candidates = query.data.behaviors.filter((item) => item.execution_state !== "metadata_only").sort((left, right) => score(right) - score(left)).slice(0, 5); function score(item: Behavior) { return `${item.title} ${item.purpose} ${item.techniques.join(" ")}`.toLowerCase().split(/\W+/).filter((word) => words.has(word)).length; } const steps = candidates.map((behavior, index) => ({ id: `local_draft_${index + 1}`, behavior_id: behavior.id, parameters: Object.fromEntries(behavior.parameters.filter((item) => item.default !== undefined).map((item) => [item.name, item.default])), inputs: {}, alternates: [] })); const localScenario: Scenario = { ...scenario, title: objective.slice(0, 80) || "Local fallback draft", purpose: objective, start: steps[0]?.id ?? "missing_start", steps, edges: steps.slice(0, -1).map((step, index) => ({ from_step: step.id, outcome: "success", to_step: steps[index + 1]!.id })), layout: undefined }; setDraftResult({ schema_version: "bluefire.ai-graph-draft-result.v1", draft_id: `local-fallback-${Date.now()}`, saved: false, scenario: localScenario, rationale: "Browser-local deterministic keyword ranking over the already loaded registered catalog.", assumptions: ["No provider or server draft endpoint was used.", "This local fallback requires full operator review."], audit: { unsaved: true, provider: { requested_provider_id: null, effective_provider_id: "browser-local-fallback", model: "keyword-ranking", attempts: 0, used_fallback: true, fallback_reason: "operator_selected_local_fallback", usage: null }, selected_behavior_ids: steps.map((step) => step.behavior_id), validation: { authority: "none", catalog_snapshot_only: true } } }); setNotice("A browser-local fallback draft was created. It remains unsaved and unauthorized."); };
  const openDraft = () => { if (!draftResult) return; const next = withDraftLayout(draftResult.scenario); setScenario(next); navigate("/builder"); };
  const handleProposalDecision = (result: AIProposalDecisionResult, review: AIProposalReview) => { client.setQueryData(["job", "planner-review", reviewJobId], result.job); setAcceptedReview(result.proposal ?? review); setFreshApproval(result.approval_request ?? undefined); setApprovalConfirmed(false); setApprovalOperator(""); setNotice(result.job.progress.approval_kind === "ai_proposal_execute" ? "Proposal accepted. Execute remains stopped at a separate fresh one-time approval envelope shown below." : `Proposal ${result.proposal.status}; job is ${sentence(result.job.state)}.`); };
  const decisions = activeRun?.planner_decisions ?? []; const managedProviders = providerResources.data?.resources ?? [];
  return <div className="page ai-page"><PageHeader eyebrow="Bounded intelligence" title="AI Planner" description="Draft unsaved graphs, configure secret-safe provider metadata, and review durable bounded runtime proposals without confusing model choice, deterministic policy, or execution approval." />
    {notice ? <Callout title="AI control plane">{notice}</Callout> : null}
    <div className="ai-hero-grid"><Panel><PanelHeader eyebrow="Autonomy policy" title="Decision authority" detail="Independent from Simulate or Execute mode; every proposal remains inside a request-specific allowlist."/><div className="autonomy-stack">{(["off", "assist", "auto"] as AutonomyLevel[]).map((level) => <button key={level} className={runConfig.autonomy === level ? "selected" : ""} onClick={() => setAutonomy(level)}><span>{level === "off" ? <Braces/> : level === "assist" ? <Bot/> : <Sparkles/>}</span><div><strong>{sentence(level)}</strong><p>{level === "off" ? "Deterministic planner only; no model calls." : level === "assist" ? "Every bounded runtime change pauses at a durable exact-digest operator review." : "May apply a policy-valid bounded change in Simulate; every Execute mutation stops for fresh one-time approval."}</p></div><i>{runConfig.autonomy === level ? <CheckCircle2/> : null}</i></button>)}</div></Panel>
      <Panel><PanelHeader eyebrow="Active runtime" title="Structured model connection" actions={<Badge tone={providerHealth === "ready" || providerHealth === "healthy" ? "success" : "warning"} dot>{sentence(providerHealth)}</Badge>}/><div className="detail-body"><Field label="Provider adapter"><select value={selectedProvider?.provider_id ?? runConfig.provider} onChange={(event) => { const provider = providers.find((item) => item.provider_id === event.target.value); setRunConfig({ ...runConfig, provider: event.target.value, model: provider?.model ?? "", endpoint: "" }); }}>{providers.map((provider) => <option value={provider.provider_id} key={provider.provider_id}>{provider.provider_id} · {sentence(provider.kind)}</option>)}</select></Field><Field label="Model" hint="Read-only control-plane configuration."><input value={selectedProvider?.model ?? runConfig.model} readOnly disabled/></Field><Field label="Endpoint" hint="Provider endpoints and resolved credentials are intentionally absent from browser metadata."><input value="" readOnly disabled placeholder="Control-plane managed"/></Field><DataList items={[{ label: "Credential boundary", value: <><KeyRound/> {selectedProvider?.credential_reference ? "Environment reference configured server-side" : "No credential required"}</> }, { label: "Proposal application", value: sentence(selectedProvider?.proposal_application ?? "not reported") }, { label: "Health meaning", value: "Configuration readiness only; not a network or quality probe" }]} /></div></Panel></div>
    <Panel className="trust-boundary"><PanelHeader eyebrow="Three separate gates" title="A model choice never becomes effect authority"/><div className="trust-flow"><div><Bot/><strong>Model proposal</strong><small>Exact observed edge and bounded registered fields</small></div><ArrowRight/><div><Braces/><strong>Schema validation</strong><small>Known IDs, typed primitives, and exact digests</small></div><ArrowRight/><div><Route/><strong>Deterministic policy</strong><small>Compatibility, exact profile, scope, tier, and retry budget</small></div><ArrowRight/><div><ShieldCheck/><strong>Proposal decision</strong><small>Assist reviews; Auto applies only policy-valid Simulate changes</small></div><ArrowRight/><div><LockKeyhole/><strong>Execute approval</strong><small>Every Execute mutation needs a fresh one-time binding</small></div></div><Callout title="Current v2 planner limits are explicit">At the exact observed next edge, the model may select that registered successor, substitute one compatible registered behavior, change allowlisted typed primitive parameters, choose an action registered for the exact active profile, or request one bounded retry. It cannot issue arbitrary commands, create capabilities, widen scope, change profile, tier, or policy, select an edge for another outcome, or runtime-apply detection or replay proposals.</Callout></Panel>
    <div className="two-column"><Panel><PanelHeader eyebrow="Runtime resources" title="Model provider drafts" detail="Activation validates and selects one stored provider; the deterministic fallback remains available."/><div className="detail-body"><Field label="Deterministic provider ID"><input value={providerId} onChange={(event) => setProviderId(event.target.value)} pattern="[a-z][a-z0-9._-]+"/></Field><Field label="Model label"><input value={providerModel} onChange={(event) => setProviderModel(event.target.value)} maxLength={200}/></Field><Button variant="secondary" onClick={() => saveProvider.mutate()} disabled={saveProvider.isPending || !providerId || !providerModel}>Save secret-free draft</Button>{managedProviders.map((resource) => <article className="secret-row" key={resource.id}><span><Bot/></span><div><strong>{resource.id}</strong><small>{sentence(String(resource.document.kind ?? "provider"))} · {String(resource.document.model ?? "Model not reported")}</small></div><div className="row-badges"><Badge tone={resource.status === "active" ? "success" : "warning"}>{sentence(resource.status)}</Badge><Button size="small" variant={resource.status === "active" ? "ghost" : "secondary"} onClick={() => lifecycle.mutate({ id: resource.id, action: resource.status === "active" ? "deactivate" : "activate" })} disabled={lifecycle.isPending}><Power/>{resource.status === "active" ? "Deactivate" : "Activate"}</Button></div></article>)}</div></Panel>
      <Panel><PanelHeader eyebrow="Unsaved graph draft" title="Objective to registered contracts" detail="The control plane normalizes known behaviors and typed parameters; it never saves, runs, or approves the result."/><div className="detail-body"><Field label="Experiment objective"><textarea rows={5} value={objective} onChange={(event) => { setObjective(event.target.value); setDraftResult(undefined); }} maxLength={4000} placeholder="Describe the defensive question to test"/></Field><Button variant="primary" onClick={() => serverDraft.mutate()} disabled={!objective.trim() || serverDraft.isPending}><Sparkles/>{serverDraft.isPending ? "Drafting through control plane" : "Generate registered draft"}</Button><Button variant="secondary" onClick={offlineDraft} disabled={!objective.trim() || serverDraft.isPending}><Braces/>Use explicit local fallback</Button><p className="field-note">The local fallback uses browser keyword matching only. Both paths produce an unsaved, unauthorized preview for operator review.</p></div></Panel></div>
    {draftResult ? <Panel><PanelHeader eyebrow="Unsaved preview" title={draftResult.scenario.title} detail={draftResult.rationale} actions={<Badge tone="warning">Not saved · not authorized</Badge>}/><div className="detail-body"><DataList items={[{ label: "Draft ID", value: <code>{draftResult.draft_id}</code> }, { label: "Provider", value: draftResult.audit.provider?.effective_provider_id ?? "Not reported" }, { label: "Model", value: draftResult.audit.provider?.model ?? "Not reported" }, { label: "Fallback", value: draftResult.audit.provider?.used_fallback ? sentence(draftResult.audit.provider.fallback_reason ?? "used") : "No fallback reported" }, { label: "Bounds", value: `${draftResult.scenario.steps.length} nodes · ${draftResult.scenario.edges.length} edges` }, { label: "Selected behaviors", value: draftResult.audit.selected_behavior_ids?.join(", ") || draftResult.scenario.steps.map((step) => step.behavior_id).join(", ") }]} />{draftResult.assumptions.length ? <Callout title="Draft assumptions"><ul>{draftResult.assumptions.map((item) => <li key={item}>{item}</li>)}</ul></Callout> : null}<details><summary>Normalization and validation audit</summary><pre>{JSON.stringify({ allowlist: draftResult.audit.allowlist, parameter_fields: draftResult.audit.parameter_fields, normalization: draftResult.audit.normalization, validation: draftResult.audit.validation }, null, 2)}</pre></details><Button variant="primary" onClick={openDraft}><Route/>Open unsaved draft in Builder</Button><p className="field-note">Opening replaces the current in-memory graph and clears any Execute confirmation. Save/version and run review remain separate actions.</p></div></Panel> : null}
    <div className="two-column"><Panel><PanelHeader eyebrow="Run lookup" title="Durable proposal record" detail="Enter the exact local durable job ID; identities and approvals are never stored."/><div className="detail-body"><Field label="Job ID"><input value={reviewJobId} onChange={(event) => setReviewJobId(event.target.value.trim())} placeholder="job-…" autoComplete="off"/></Field>{jobQuery.isError ? <Callout tone="danger" title="Job unavailable">{jobQuery.error.message}</Callout> : jobQuery.isPending && reviewJobId ? <LoadingState label="Loading durable job"/> : jobQuery.data ? <DataList items={[{ label: "State", value: sentence(jobQuery.data.state) }, { label: "Approval kind", value: sentence(String(jobQuery.data.progress.approval_kind ?? "none")) }, { label: "Run reference", value: String(jobQuery.data.result_ref ?? jobQuery.data.progress.run_id ?? "Not available") }]} /> : <Callout title="No job selected">Use the Runs workspace for a live job, or paste a durable job ID here for proposal audit.</Callout>}</div></Panel><Panel><PanelHeader eyebrow="Completed run audit" title="Planner decisions" actions={<Badge>{decisions.length}</Badge>}/>{decisions.length ? <div className="decision-list">{decisions.map((decision, index) => <article key={index}><span>{String(index + 1).padStart(2, "0")}</span><pre>{JSON.stringify(decision, null, 2)}</pre></article>)}</div> : <Callout title="No completed-run decisions loaded">Durable proposal review uses the job-bound panel below. Completed canonical decisions appear here after a run record is loaded.</Callout>}</Panel></div>
    {jobQuery.data ? <ProposalReviewWorkspace job={jobQuery.data} onDecision={handleProposalDecision} onReviewLoaded={(review) => { if (review.status === "accepted") setAcceptedReview(review); }}/> : null}
    {jobQuery.data?.state === "awaiting_approval" && jobQuery.data.progress.approval_kind === "ai_proposal_execute" ? (freshApproval ?? jobQuery.data.approval_request) && acceptedReview ? <PlannerContinuationApproval request={(freshApproval ?? jobQuery.data.approval_request)!} review={acceptedReview} confirmed={approvalConfirmed} operator={approvalOperator} pending={approveContinuation.isPending} onConfirmed={setApprovalConfirmed} onOperator={setApprovalOperator} onApprove={() => approveContinuation.mutate()}/> : <Callout tone="danger" title="Fresh Execute envelope is not loaded">This job is waiting for a proposal-continuation approval, but the nonce-free public binding or accepted proposal review is unavailable. Approval is intentionally disabled; never approve a job whose fresh digests are not displayed.</Callout> : null}
  </div>;
}

function withDraftLayout(scenario: Scenario): Scenario {
  return { ...scenario, layout: Object.fromEntries(scenario.steps.map((step, index) => [step.id, { x: 70 + (index % 4) * 300, y: 110 + Math.floor(index / 4) * 230 }])) };
}

function PlannerContinuationApproval({ request, review, confirmed, operator, pending, onConfirmed, onOperator, onApprove }: { request: Record<string, unknown>; review: AIProposalReview; confirmed: boolean; operator: string; pending: boolean; onConfirmed: (value: boolean) => void; onOperator: (value: string) => void; onApprove: () => void }) {
  const continuation = review.resolution?.continuation && typeof review.resolution.continuation === "object" ? review.resolution.continuation as Record<string, unknown> : undefined;
  const ready = ["approval_id", "state_digest", "plan_digest", "target_scope_digest", "profile_id", "maximum_tier"].every((field) => typeof request[field] === "string") && Boolean(continuation?.execute_approval_binding_digest);
  return <Panel><PanelHeader eyebrow="Separate effect authorization" title="Fresh Execute approval after proposal acceptance" detail="Accepting the registered behavior did not authorize runner effects." actions={<Badge tone="warning">Awaiting one-time approval</Badge>}/>{ready ? <><DataList items={[{ label: "Approval request", value: <code>{String(request.approval_id)}</code> }, { label: "Proposal record", value: <code>{review.proposal_record_id}</code> }, { label: "State digest", value: <code>{String(request.state_digest)}</code> }, { label: "Plan digest", value: <code>{String(request.plan_digest)}</code> }, { label: "Scope digest", value: <code>{String(request.target_scope_digest)}</code> }, { label: "Profile / tier", value: `${String(request.profile_id)} / ${sentence(String(request.maximum_tier))}` }, { label: "Continuation binding", value: <code>{String(continuation?.execute_approval_binding_digest)}</code> }, { label: "Selected behavior", value: <code>{String(continuation?.selected_behavior_id ?? review.record.proposal?.selected_behavior_id ?? "Not reported")}</code> }]} /><Callout tone="warning" title="Proposal, policy, and approval remain distinct">The server will reconstruct policy and plan state, compare this fresh binding, atomically consume it, and refuse reuse of the original Execute approval.</Callout><label className="check-row"><input type="checkbox" checked={confirmed} onChange={(event) => onConfirmed(event.target.checked)} disabled={pending}/><span><strong>I approve this exact proposal-continuation envelope once</strong><small>Unchecked by default and never persisted</small></span></label><Field label="Operator identity for fresh Execute approval"><input value={operator} onChange={(event) => onOperator(event.target.value)} autoComplete="off" maxLength={128} disabled={pending}/></Field><Button variant="primary" onClick={onApprove} disabled={!confirmed || !operator.trim() || pending}><LockKeyhole/>{pending ? "Applying fresh approval" : "Approve and release continuation"}</Button></> : <Callout tone="danger" title="Incomplete fresh binding">Approval remains disabled until every public binding digest and continuation digest is present.</Callout>}</Panel>;
}
