import * as Dialog from "@radix-ui/react-dialog";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, Archive, Box, CheckCircle2, ExternalLink, FileCode2, Filter, Plus, Power, Search, Server, ShieldCheck, Unplug } from "lucide-react";
import { useState } from "react";
import { api } from "../lib/api";
import type { Behavior, RunnerProbe, RunnerProfile } from "../types";
import { Badge, Button, Callout, DataList, EmptyState, ErrorState, Field, LoadingState, Modal, PageHeader, Panel, PanelHeader, sentence } from "../components/Primitives";

function tierTone(tier: string) { return tier === "restricted" ? "danger" as const : tier === "controlled" ? "warning" as const : "success" as const; }

export function BehaviorsPage() {
  const query = useQuery({ queryKey: ["catalog"], queryFn: api.catalog });
  const [search, setSearch] = useState(""); const [platform, setPlatform] = useState("all"); const [tier, setTier] = useState("all"); const [selectedId, setSelectedId] = useState<string>();
  if (query.isPending) return <LoadingState label="Loading behavior registry" />;
  if (query.isError) return <ErrorState error={query.error} retry={() => query.refetch()} />;
  const behaviors = query.data.behaviors.filter((item) => {
    const text = `${item.id} ${item.title} ${item.purpose} ${item.capabilities.join(" ")} ${item.techniques.join(" ")}`.toLowerCase();
    return (!search || text.includes(search.toLowerCase())) && (platform === "all" || item.platforms.includes(platform)) && (tier === "all" || item.safety_tier === tier);
  });
  const selected = query.data.behaviors.find((item) => item.id === selectedId) ?? behaviors[0];
  const platforms = [...new Set(query.data.behaviors.flatMap((item) => item.platforms))].sort();
  return <div className="page">
    <PageHeader eyebrow="Behavior registry" title="Neutral, typed behavior contracts" description="Behaviors define intent, artifacts, expected telemetry, policy requirements, and the installed implementations that may satisfy them." />
    <div className="catalog-layout">
      <Panel className="catalog-list-panel">
        <div className="catalog-filters"><label className="search-box"><Search/><span className="sr-only">Search behaviors</span><input aria-label="Search behaviors" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search behavior, capability, technique" /></label><label><span className="sr-only">Platform</span><select aria-label="Filter by platform" value={platform} onChange={(event) => setPlatform(event.target.value)}><option value="all">All platforms</option>{platforms.map((item) => <option key={item}>{item}</option>)}</select></label><label><span className="sr-only">Safety tier</span><select aria-label="Filter by safety tier" value={tier} onChange={(event) => setTier(event.target.value)}><option value="all">All tiers</option><option value="safe">Safe</option><option value="controlled">Controlled</option><option value="restricted">Restricted</option></select></label></div>
        <div className="catalog-count"><Filter/> {behaviors.length} of {query.data.behaviors.length} behaviors</div>
        <div className="behavior-table" role="list">{behaviors.map((item) => <button role="listitem" className={selected?.id === item.id ? "selected" : ""} onClick={() => setSelectedId(item.id)} key={item.id}><span className={`registry-icon tier-${item.safety_tier}`}><FileCode2/></span><span><strong>{item.title}</strong><small>{item.id}</small><em>{item.purpose}</em></span><span className="row-badges"><Badge tone={tierTone(item.safety_tier)}>{item.safety_tier}</Badge><Badge tone={item.execution_state === "action" ? "success" : item.execution_state === "simulation" ? "info" : "neutral"}>{sentence(item.execution_state)}</Badge></span></button>)}</div>
        {!behaviors.length ? <EmptyState title="No matching behaviors" description="Clear one of the filters to broaden the registry view." /> : null}
      </Panel>
      {selected ? <BehaviorDetail behavior={selected} /> : null}
    </div>
  </div>;
}

function BehaviorDetail({ behavior }: { behavior: Behavior }) {
  return <Panel className="detail-panel"><PanelHeader eyebrow="Contract detail" title={behavior.title} detail={behavior.purpose} actions={<Badge tone={tierTone(behavior.safety_tier)}>{behavior.safety_tier}</Badge>} />
    <div className="detail-body">
      {behavior.execution_state !== "action" ? <Callout tone="warning" title={sentence(behavior.execution_state)}>{behavior.limitations[0] ?? "No installed Execute action is advertised for this behavior."}</Callout> : null}
      <DataList items={[{ label: "Behavior ID", value: <code>{behavior.id}</code> }, { label: "Platforms", value: behavior.platforms.join(", ") || "None" }, { label: "Techniques", value: behavior.techniques.join(", ") || "Not mapped" }, { label: "Simulation", value: behavior.simulation_id ? <code>{behavior.simulation_id}</code> : "Unavailable" }, { label: "Actions", value: behavior.action_ids.length ? behavior.action_ids.map((item) => <code key={item}>{item}</code>) : "None installed" }]} />
      <section className="detail-section"><h3>Typed contract</h3><div className="contract-columns"><div><h4>Inputs</h4>{behavior.inputs.length ? behavior.inputs.map((item) => <div className="port-row" key={item.name}><span>{item.name}{item.required ? " *" : ""}</span><code>{item.type}</code></div>) : <p>No artifact inputs.</p>}</div><div><h4>Outputs</h4>{behavior.outputs.length ? behavior.outputs.map((item) => <div className="port-row" key={item.name}><span>{item.name}</span><code>{item.type}</code></div>) : <p>No emitted artifacts.</p>}</div></div></section>
      <section className="detail-section"><h3>Expected telemetry</h3><div className="chip-list">{behavior.telemetry.map((item) => <Badge key={item} tone="info">{item}</Badge>)}</div>{!behavior.telemetry.length ? <p>None declared.</p> : null}</section>
      <section className="detail-section"><h3>Detection value</h3>{behavior.detection_hints.length ? <ul>{behavior.detection_hints.map((item) => <li key={item}>{item}</li>)}</ul> : <p>No hypothesis declared.</p>}</section>
      <section className="detail-section"><h3>Capabilities</h3><div className="chip-list">{behavior.capabilities.map((item) => <Badge key={item}>{item}</Badge>)}</div></section>
    </div>
  </Panel>;
}

export function RunnerProfilesPage() {
  const query = useQuery({ queryKey: ["catalog"], queryFn: api.catalog });
  const resourcesQuery = useQuery({ queryKey: ["resources", "runner-profiles"], queryFn: () => api.resources("runner-profiles") });
  const queryClient = useQueryClient(); const [notice, setNotice] = useState<string>();
  const saveMutation = useMutation({ mutationFn: (profile: RunnerProfile) => { const { secrets, ...secretSafeProfile } = profile; void secrets; return api.saveResource("runner-profiles", profile.id, secretSafeProfile as unknown as Record<string, unknown>, "draft"); }, onSuccess: ({ resource }) => { setNotice(`${resource.id} saved as a durable draft.`); queryClient.invalidateQueries({ queryKey: ["resources", "runner-profiles"] }); }, onError: (error) => setNotice(error instanceof Error ? error.message : "The runner profile could not be saved.") });
  const lifecycleMutation = useMutation({ mutationFn: ({ id, action }: { id: string; action: "activate" | "deactivate" }) => action === "activate" ? api.activateResource("runner-profiles", id) : api.deactivateResource("runner-profiles", id), onSuccess: ({ resource }) => { setNotice(`${resource.id} is now ${resource.status}. Runtime selection was refreshed by the control plane.`); queryClient.invalidateQueries({ queryKey: ["resources", "runner-profiles"] }); queryClient.invalidateQueries({ queryKey: ["catalog"] }); }, onError: (error) => setNotice(error instanceof Error ? error.message : "The runner profile lifecycle action was refused.") });
  if (query.isPending) return <LoadingState label="Loading runner profiles" />;
  if (query.isError) return <ErrorState error={query.error} retry={() => query.refetch()} />;
  const managedProfiles = (resourcesQuery.data?.resources ?? []).map((resource) => ({ profile: resource.document as unknown as RunnerProfile, resource })).filter((item) => item.profile?.id && Array.isArray(item.profile.platforms)); const managedIds = new Set(managedProfiles.map((item) => item.profile.id));
  const profiles = [...query.data.runner_profiles.filter((item) => !managedIds.has(item.id)).map((profile) => ({ profile, resource: null })), ...managedProfiles];
  return <div className="page"><PageHeader eyebrow="Authorization envelopes" title="Runner profiles" description="Profiles bind environment, scope, capabilities, safety tiers, approvals, budgets, and cleanup before a task can reach a runner." actions={<Modal title="Draft runner profile" description="Save a secret-safe profile document to the durable local control-plane store. A draft does not enroll or connect a runner." trigger={<Button variant="primary"><Plus/>New profile</Button>}><ProfileForm onCreate={(profile) => saveMutation.mutate(profile)} saving={saveMutation.isPending}/></Modal>} />
    {notice ? <Callout title="Runner profile">{notice}</Callout> : resourcesQuery.isError ? <Callout tone="warning" title="Managed profiles unavailable">Catalog profiles remain visible; durable drafts could not be loaded.</Callout> : null}
    <Callout title="Configuration is not connectivity">A profile can be valid while its runner is offline. Verify runner identity and inventory on the Runners page before Execute.</Callout>
    <div className="profile-grid">{profiles.map(({ profile, resource }) => <Panel className="profile-card" key={profile.id}><header><span className={`registry-icon ${profile.mode === "execute" ? "tier-controlled" : "tier-safe"}`}>{profile.mode === "execute" ? <ShieldCheck/> : <Archive/>}</span><div><h2>{profile.id}</h2><p>{sentence(profile.environment_type)}</p></div><div className="row-badges"><Badge tone={profile.mode === "execute" ? "warning" : "info"}>{profile.mode}</Badge><Badge tone={resource?.status === "active" ? "success" : resource?.status === "inactive" ? "neutral" : "warning"}>{resource ? sentence(resource.status) : "Configuration baseline"}</Badge></div></header><DataList items={[{ label: "Scope", value: profile.scope.join(", ") }, { label: "Platforms", value: profile.platforms.join(", ") }, { label: "Safety tiers", value: profile.safety_tiers.join(", ") }, { label: "Approval", value: profile.approval_required ? "Required" : "Not required" }, { label: "Cleanup", value: sentence(profile.cleanup_policy) }]} /><div className="budget-strip"><span><small>Seconds</small><strong>{profile.budgets.max_seconds ?? "—"}</strong></span><span><small>Steps</small><strong>{profile.budgets.max_steps ?? "—"}</strong></span><span><small>Bytes</small><strong>{profile.budgets.max_bytes ? `${Math.round(profile.budgets.max_bytes / 1_048_576)} MiB` : "—"}</strong></span></div><footer><Badge tone="neutral">{profile.capabilities.length} capabilities</Badge><Badge tone="neutral">{profile.enabled_actions.length} actions</Badge>{resource ? <Button size="small" variant={resource.status === "active" ? "ghost" : "secondary"} disabled={lifecycleMutation.isPending} onClick={() => lifecycleMutation.mutate({ id: profile.id, action: resource.status === "active" ? "deactivate" : "activate" })}><Power/>{resource.status === "active" ? "Deactivate" : "Validate & activate"}</Button> : null}</footer></Panel>)}</div>
  </div>;
}

function ProfileForm({ onCreate, saving }: { onCreate: (profile: RunnerProfile) => void; saving: boolean }) {
  const [id, setId] = useState("local-sandbox-execute.v1"); const [mode, setMode] = useState<"simulate" | "execute">("execute"); const [runnerEnv, setRunnerEnv] = useState("BLUEFIRE_RUNNER_BINARY"); const [sandboxEnv, setSandboxEnv] = useState("BLUEFIRE_SANDBOX_ROOT");
  return <form className="dialog-form" onSubmit={(event) => { event.preventDefault(); onCreate({ id, mode, environment_type: "disposable", platforms: ["linux"], runner_binary: { env: runnerEnv }, sandbox_root: { env: sandboxEnv }, scope: ["sandbox.workspace"], network_allowlist: ["127.0.0.1/32"], capabilities: ["filesystem.read", "filesystem.write"], safety_tiers: ["safe", "controlled"], approval_required: mode === "execute", enabled_actions: [], blocked_actions: [], cleanup_policy: "always", budgets: { max_seconds: 120, max_steps: 20, max_artifacts: 100, max_bytes: 8_388_608 }, secrets: {} }); }}><Field label="Profile ID"><input value={id} onChange={(event) => setId(event.target.value)} pattern="[a-z][a-z0-9._-]+" required /></Field><Field label="Mode"><select value={mode} onChange={(event) => setMode(event.target.value as "simulate" | "execute")}><option value="simulate">Simulate</option><option value="execute">Execute</option></select></Field><Field label="Runner binary environment reference" hint="Only the variable name is stored."><input value={runnerEnv} onChange={(event) => setRunnerEnv(event.target.value.toUpperCase())} pattern="[A-Z_][A-Z0-9_]*" required/></Field><Field label="Sandbox root environment reference" hint="No resolved path enters browser state."><input value={sandboxEnv} onChange={(event) => setSandboxEnv(event.target.value.toUpperCase())} pattern="[A-Z_][A-Z0-9_]*" required/></Field><Field label="Authorized scope"><input value="sandbox.workspace" readOnly /></Field><div className="dialog-actions"><Dialog.Close asChild><Button type="button" variant="ghost">Cancel</Button></Dialog.Close><Dialog.Close asChild><Button type="button" onClick={(event) => { const form = event.currentTarget.form; if (!form?.reportValidity()) { event.preventDefault(); return; } form.requestSubmit(); }} variant="primary" disabled={saving}>{saving ? "Saving" : "Save durable draft"}</Button></Dialog.Close></div></form>;
}

export function RunnersPage() {
  const query = useQuery({ queryKey: ["catalog"], queryFn: api.catalog });
  const resourcesQuery = useQuery({ queryKey: ["resources", "runners"], queryFn: () => api.resources("runners") }); const profilesQuery = useQuery({ queryKey: ["resources", "runner-profiles"], queryFn: () => api.resources("runner-profiles") }); const queryClient = useQueryClient(); const [notice, setNotice] = useState<string>(); const [probe, setProbe] = useState<RunnerProbe>();
  const saveMutation = useMutation({ mutationFn: (runner: { id: string; label: string; platform: string; binaryEnv: string }) => api.saveResource("runners", runner.id, { label: runner.label, platform: runner.platform, transport: "local", binary_reference: { env: runner.binaryEnv }, connectivity: "not_verified" }, "draft"), onSuccess: ({ resource }) => { setNotice(`${resource.id} saved as a runner record. No process was started and connectivity remains unverified.`); queryClient.invalidateQueries({ queryKey: ["resources", "runners"] }); }, onError: (error) => setNotice(error instanceof Error ? error.message : "The runner record could not be saved.") });
  const probeMutation = useMutation({ mutationFn: (profileId: string) => api.probeRunnerProfile(profileId), onSuccess: (result) => { setProbe(result); setNotice(`Runner probe for ${result.profile_id} returned sanitized ${result.health.state} health.`); }, onError: (error) => { setProbe(undefined); setNotice(error instanceof Error ? error.message : "The bounded runner probe was refused."); } });
  if (query.isPending) return <LoadingState label="Checking runner inventory" />;
  if (query.isError) return <ErrorState error={query.error} retry={() => query.refetch()} />;
  const executeProfiles = query.data.runner_profiles.filter((item) => item.mode === "execute");
  const managedRunners = resourcesQuery.data?.resources ?? [];
  const storedProfiles = profilesQuery.data?.resources ?? [];
  return <div className="page"><PageHeader eyebrow="Execution boundary" title="Runners" description="Register secret-safe runner records, verify capability inventory separately, and keep transport identity outside browser state." actions={<Modal title="Register runner record" description="Persist a bounded runner reference. This does not launch, enroll, authenticate, or attest a runner." trigger={<Button variant="primary"><Plus/>Register record</Button>}><RunnerRecordForm onCreate={(runner) => saveMutation.mutate(runner)} saving={saveMutation.isPending}/></Modal>} />
    {notice ? <Callout title="Runner record">{notice}</Callout> : resourcesQuery.isError ? <Callout tone="warning" title="Runner records unavailable">Profile metadata remains visible.</Callout> : null}
    <Callout title="Bounded probe boundary">A probe resolves only the stored profile’s server-side environment reference. The response omits paths, environment values, stderr, raw inventory fields, and exception text.</Callout>
    <div className="runner-grid">{managedRunners.map((runner) => <Panel className="runner-card" key={runner.id}><header><span className="runner-glyph"><Server/></span><div><Badge tone="neutral" dot>{sentence(runner.status)}</Badge><h2>{String(runner.document.label ?? runner.id)}</h2><p>{sentence(String(runner.document.transport ?? "unverified transport"))}</p></div></header><DataList items={[{ label: "Identity", value: <code>{runner.id}</code> }, { label: "Platform", value: String(runner.document.platform ?? "Not reported") }, { label: "Connectivity", value: "Not verified by this record" }]} /></Panel>)}{storedProfiles.map((resource) => { const profile = resource.document as unknown as RunnerProfile; return <Panel className="runner-card" key={resource.id}><header><span className="runner-glyph"><Server/></span><div><Badge tone={resource.status === "active" ? "success" : "warning"} dot>{sentence(resource.status)}</Badge><h2>{resource.id}</h2><p>{sentence(String(profile.environment_type ?? "stored profile"))}</p></div></header><DataList items={[{ label: "Probe authority", value: "Stored profile only" }, { label: "Platforms", value: Array.isArray(profile.platforms) ? profile.platforms.join(", ") : "Not reported" }, { label: "Enabled actions", value: Array.isArray(profile.enabled_actions) ? String(profile.enabled_actions.length) : "Not reported" }]} /><footer><Button size="small" onClick={() => probeMutation.mutate(resource.id)} disabled={probeMutation.isPending}>{probeMutation.isPending && probe?.profile_id === resource.id ? <Activity className="spin"/> : <Server/>}Probe health & inventory</Button></footer></Panel>; })}{!storedProfiles.length ? executeProfiles.map((profile) => <Panel className="runner-card ghost-runner" key={profile.id}><header><span className="runner-glyph"><Unplug/></span><div><Badge tone="warning">Configuration baseline</Badge><h2>{profile.id}</h2><p>{sentence(profile.environment_type)}</p></div></header><p>Persist this profile before requesting a bounded runtime probe.</p><div className="chip-list">{profile.platforms.map((item) => <Badge key={item}>{item}</Badge>)}</div></Panel>) : null}</div>
    {probe ? <Panel><PanelHeader eyebrow="Sanitized inventory" title={probe.profile_id} actions={<Badge tone={probe.health.state === "ready" ? "success" : probe.health.state === "degraded" ? "warning" : "danger"} dot>{sentence(probe.health.state)}</Badge>}/><Callout tone={probe.health.state === "ready" ? "success" : "warning"} title="Runner health">{probe.health.message}</Callout><DataList items={[{ label: "Version", value: probe.version ?? "Unavailable" }, { label: "Platform", value: probe.platform ? sentence(probe.platform) : "Unavailable" }, { label: "Missing profile actions", value: probe.health.missing_actions?.join(", ") || "None reported" }]} />{probe.actions.length ? <div className="table-scroll"><table><thead><tr><th>Allowlisted action ID</th><th>Version</th><th>Readiness</th></tr></thead><tbody>{probe.actions.map((action) => <tr key={action.action_id}><td><code>{action.action_id}</code></td><td>{action.version ?? "Not reported"}</td><td><Badge tone={action.readiness === "ready" ? "success" : "neutral"}>{sentence(action.readiness ?? "not reported")}</Badge></td></tr>)}</tbody></table></div> : <EmptyState title="No actions reported" description="Unavailable inventory does not authorize Execute."/>}</Panel> : null}
    <Panel><PanelHeader eyebrow="Enrollment checklist" title="Bring a runner online safely"/><ol className="step-list"><li><span>1</span><div><strong>Build the standalone Rust runner</strong><p>Use the pinned toolchain and verify the packaged binary.</p></div></li><li><span>2</span><div><strong>Attach an authorization profile</strong><p>Scope, tiers, actions, budgets, and cleanup remain explicit.</p></div></li><li><span>3</span><div><strong>Verify identity and inventory</strong><p>Execute stays unavailable until health and capability checks pass.</p></div></li></ol></Panel>
  </div>;
}

function RunnerRecordForm({ onCreate, saving }: { onCreate: (runner: { id: string; label: string; platform: string; binaryEnv: string }) => void; saving: boolean }) {
  const [id, setId] = useState("runner.local-sandbox.v1"); const [label, setLabel] = useState("Local sandbox runner"); const [platform, setPlatform] = useState("linux"); const [binaryEnv, setBinaryEnv] = useState("BLUEFIRE_RUNNER_BINARY");
  return <form className="dialog-form" onSubmit={(event) => { event.preventDefault(); onCreate({ id, label, platform, binaryEnv }); }}><Field label="Runner record ID"><input value={id} onChange={(event) => setId(event.target.value)} pattern="[a-z][a-z0-9._-]+" required/></Field><Field label="Display label"><input value={label} onChange={(event) => setLabel(event.target.value)} required/></Field><Field label="Platform"><select value={platform} onChange={(event) => setPlatform(event.target.value)}><option value="linux">Linux</option><option value="windows">Windows</option><option value="macos">macOS</option></select></Field><Field label="Binary environment reference" hint="The environment-variable name is saved; its resolved value never enters the browser."><input value={binaryEnv} onChange={(event) => setBinaryEnv(event.target.value.toUpperCase())} pattern="[A-Z_][A-Z0-9_]*" required/></Field><div className="dialog-actions"><Dialog.Close asChild><Button type="button" variant="ghost">Cancel</Button></Dialog.Close><Dialog.Close asChild><Button type="button" onClick={(event) => { const form = event.currentTarget.form; if (!form?.reportValidity()) { event.preventDefault(); return; } form.requestSubmit(); }} variant="primary" disabled={saving}>{saving ? "Saving" : "Save runner record"}</Button></Dialog.Close></div></form>;
}

export function ActionsPage() {
  const query = useQuery({ queryKey: ["catalog"], queryFn: api.catalog }); const resourcesQuery = useQuery({ queryKey: ["resources", "plugins"], queryFn: () => api.resources("plugins") }); const queryClient = useQueryClient(); const [search, setSearch] = useState(""); const [notice, setNotice] = useState<string>();
  const saveMutation = useMutation({ mutationFn: (plugin: PluginDraft) => api.saveResource("plugins", plugin.id, { schema_version: "bluefire.plugin.v1", id: plugin.id, name: plugin.name, version: plugin.version, enabled: plugin.enabled, trust: plugin.trust, integrity: { algorithm: "sha256", digest: plugin.digest }, license: plugin.license, provenance: { source: plugin.source, reference: plugin.reference, license: plugin.license, derived: false, notes: "Locally reviewed declarative metadata; executable loading remains disabled." }, permissions: ["catalog.read"], capabilities: [], behavior_ids: [], action_ids: [] }), onSuccess: ({ resource }) => { setNotice(`${resource.id} manifest saved as ${resource.status}. No package was downloaded or installed.`); queryClient.invalidateQueries({ queryKey: ["resources", "plugins"] }); }, onError: (error) => setNotice(error instanceof Error ? error.message : "The plugin manifest could not be saved.") });
  const lifecycleMutation = useMutation({ mutationFn: ({ id, action }: { id: string; action: "activate" | "deactivate" }) => action === "activate" ? api.activateResource("plugins", id) : api.deactivateResource("plugins", id), onSuccess: (result) => { setNotice(`${result.resource.id} is ${result.resource.status}. Registration is metadata-only; executable loading and dynamic actions remain disabled.`); queryClient.invalidateQueries({ queryKey: ["resources", "plugins"] }); }, onError: (error) => setNotice(error instanceof Error ? error.message : "The plugin lifecycle action was refused.") });
  if (query.isPending) return <LoadingState label="Loading action inventory" />;
  if (query.isError) return <ErrorState error={query.error} retry={() => query.refetch()} />;
  const actions = query.data.actions.filter((item) => `${item.id} ${item.title} ${item.purpose} ${item.capabilities.join(" ")}`.toLowerCase().includes(search.toLowerCase()));
  const plugins = resourcesQuery.data?.resources ?? [];
  const inventory = resourcesQuery.data?.inventory;
  return <div className="page"><PageHeader eyebrow="Installed capability" title="Actions & plugins" description="Reviewed, versioned action contracts are the only path from orchestration intent to runner effects." actions={<Modal title="Add plugin manifest" description="Persist a strict declarative manifest. This does not download, verify bytes, install code, or register dynamic actions." trigger={<Button variant="primary"><Plus/>Add manifest</Button>}><PluginManifestForm onCreate={(plugin) => saveMutation.mutate(plugin)} saving={saveMutation.isPending}/></Modal>} />
    {notice ? <Callout title="Plugin manifest">{notice}</Callout> : resourcesQuery.isError ? <Callout tone="warning" title="Plugin manifests unavailable">Built-in action contracts remain visible.</Callout> : null}
    <Panel><div className="catalog-filters"><label className="search-box"><Search/><span className="sr-only">Search actions</span><input aria-label="Search actions" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search actions or capabilities" /></label><Badge tone="success">{actions.length} registered</Badge></div><div className="table-scroll"><table><thead><tr><th>Action</th><th>Platforms</th><th>Safety</th><th>Effects</th><th>Cleanup</th></tr></thead><tbody>{actions.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><code>{item.id}</code><small>{item.purpose}</small></td><td>{item.platforms.join(", ")}</td><td><Badge tone={tierTone(item.safety_tier)}>{item.safety_tier}</Badge></td><td><Badge tone={item.mutates ? "warning" : "success"}>{item.mutates ? "Mutating" : "Read only"}</Badge></td><td>{item.cleanup_action_id ? <code>{item.cleanup_action_id}</code> : item.id.includes("cleanup") ? "Self" : "Not declared"}</td></tr>)}</tbody></table></div></Panel>
    <div className="two-column"><Panel><PanelHeader eyebrow="Package boundary" title="Action SDK requirements"/><ul className="check-list"><li><CheckCircle2/>Versioned ID and typed parameters</li><li><CheckCircle2/>Capabilities, tier, target, and scope</li><li><CheckCircle2/>Preflight, receipts, and deterministic test hooks</li><li><CheckCircle2/>Cleanup and partial-result handling</li></ul>{inventory ? <DataList items={[{ label: "Manifest inventory", value: String(inventory.manifest_count) }, { label: "Active metadata IDs", value: inventory.active_manifest_ids.join(", ") || "None" }, { label: "Executable loading", value: inventory.executable_loading ? "Enabled" : "Disabled" }, { label: "Dynamic actions", value: inventory.dynamic_actions ? "Enabled" : "Disabled" }, { label: "Python entry points", value: inventory.python_entry_points ? "Enabled" : "Disabled" }]} /> : null}</Panel><Panel><PanelHeader eyebrow="Third-party content" title="Declarative plugin manifests" actions={<Badge>{plugins.length}</Badge>}/>{plugins.length ? <div className="detail-body">{plugins.map((plugin) => <article className="secret-row" key={plugin.id}><span><Box/></span><div><strong>{String(plugin.document.name ?? plugin.id)}</strong><small>{plugin.id} · {String(plugin.document.version ?? "Version not declared")}</small></div><div className="row-badges"><Badge tone={plugin.status === "active" ? "success" : plugin.status === "ready" ? "info" : "warning"}>{sentence(plugin.status)}</Badge><Button size="small" variant={plugin.status === "active" ? "ghost" : "secondary"} disabled={lifecycleMutation.isPending || !["ready", "inactive", "active"].includes(plugin.status)} onClick={() => lifecycleMutation.mutate({ id: plugin.id, action: plugin.status === "active" ? "deactivate" : "activate" })}><Power/>{plugin.status === "active" ? "Deactivate" : "Activate metadata"}</Button></div></article>)}<Callout title="Metadata-only activation">Active means the reviewed manifest metadata is inventoried. It never installs or loads plugin code and grants no dynamic action capability.</Callout></div> : <EmptyState icon={<Box/>} title="No external plugin manifests" description="The current catalog contains built-in reviewed actions. Add only secret-safe provenance metadata here." />}</Panel></div>
  </div>;
}

interface PluginDraft { id: string; name: string; version: string; source: string; reference: string; license: string; digest: string; trust: "untrusted" | "reviewed" | "trusted"; enabled: boolean }

function PluginManifestForm({ onCreate, saving }: { onCreate: (plugin: PluginDraft) => void; saving: boolean }) {
  const [id, setId] = useState("plugin.local-review.v1"); const [name, setName] = useState("Local review plugin"); const [version, setVersion] = useState("0.1.0"); const [source, setSource] = useState("Local reviewed source"); const [reference, setReference] = useState("https://example.invalid/reviewed-release"); const [license, setLicense] = useState("Review required"); const [digest, setDigest] = useState(""); const [trust, setTrust] = useState<PluginDraft["trust"]>("untrusted"); const [enabled, setEnabled] = useState(false);
  return <form className="dialog-form" onSubmit={(event) => { event.preventDefault(); onCreate({ id, name, version, source, reference, license, digest, trust, enabled }); }}><Field label="Plugin ID"><input value={id} onChange={(event) => setId(event.target.value)} pattern="[a-z][a-z0-9._-]+\.v[0-9]+" required/></Field><Field label="Display name"><input value={name} onChange={(event) => setName(event.target.value)} required/></Field><Field label="Version"><input value={version} onChange={(event) => setVersion(event.target.value)} pattern="[0-9]+\.[0-9]+\.[0-9]+" required/></Field><Field label="Reviewed source"><input value={source} onChange={(event) => setSource(event.target.value)} required/></Field><Field label="Pinned provenance reference" hint="Metadata only; the browser does not fetch it."><input type="url" value={reference} onChange={(event) => setReference(event.target.value)} required/></Field><Field label="Reviewed SHA-256" hint="Exactly 64 lowercase hex characters. BlueFire stores this identity but does not fetch or hash bytes."><input value={digest} onChange={(event) => setDigest(event.target.value.toLowerCase())} pattern="[0-9a-f]{64}" maxLength={64} required/></Field><Field label="Trust review"><select value={trust} onChange={(event) => setTrust(event.target.value as PluginDraft["trust"])}><option value="untrusted">Untrusted</option><option value="reviewed">Reviewed</option><option value="trusted">Trusted</option></select></Field><Field label="License"><input value={license} onChange={(event) => setLicense(event.target.value)} required/></Field><label className="check-row"><input type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)}/><span><strong>Declaratively eligible</strong><small>Does not load code; reviewed/trusted metadata with a non-placeholder digest is still required for activation.</small></span></label><div className="dialog-actions"><Dialog.Close asChild><Button type="button" variant="ghost">Cancel</Button></Dialog.Close><Dialog.Close asChild><Button type="button" onClick={(event) => { const form = event.currentTarget.form; if (!form?.reportValidity()) { event.preventDefault(); return; } form.requestSubmit(); }} variant="primary" disabled={saving}>{saving ? "Saving" : "Save strict manifest"}</Button></Dialog.Close></div></form>;
}

const seededSources = [
  { id: "mitre.attack.v1", name: "MITRE ATT&CK", kind: "STIX behavior reference", url: "https://attack.mitre.org/", license: "Terms apply", status: "not_synced" },
  { id: "sigmahq.v1", name: "SigmaHQ", kind: "Detection baseline", url: "https://github.com/SigmaHQ/sigma", license: "Repository-specific", status: "not_synced" },
  { id: "atomic-red-team.v1", name: "Atomic Red Team", kind: "Reviewed emulation reference", url: "https://github.com/redcanaryco/atomic-red-team", license: "MIT", status: "not_synced" },
  { id: "elastic-detection-rules.v1", name: "Elastic detection rules", kind: "Public baseline", url: "https://github.com/elastic/detection-rules", license: "Elastic License 2.0", status: "not_synced" },
];

export function ResearchSourcesPage() {
  const query = useQuery({ queryKey: ["resources", "research-sources"], queryFn: () => api.resources("research-sources") }); const queryClient = useQueryClient(); const [notice, setNotice] = useState<string>();
  const saveMutation = useMutation({ mutationFn: (source: { id: string; name: string; kind: string; url: string; license: string }) => api.saveResource("research-sources", source.id, { name: source.name, kind: source.kind, url: source.url, license: source.license, use: "comparative_reference" }, "draft"), onSuccess: ({ resource }) => { setNotice(`${resource.id} saved as a durable source draft. No remote content was fetched.`); queryClient.invalidateQueries({ queryKey: ["resources", "research-sources"] }); }, onError: (error) => setNotice(error instanceof Error ? error.message : "The research source could not be saved.") });
  const managed = (query.data?.resources ?? []).map((item) => ({ id: item.id, name: String(item.document.name ?? item.id), kind: String(item.document.kind ?? "Unclassified"), url: String(item.document.url ?? ""), license: String(item.document.license ?? "Review required"), status: item.status })); const managedIds = new Set(managed.map((item) => item.id)); const sources = [...seededSources.filter((item) => !managedIds.has(item.id)), ...managed];
  return <div className="page"><PageHeader eyebrow="Research provenance" title="Research sources" description="Pin authoritative public material, record license and retrieval metadata, and distinguish imported, adapted, inspired, and comparative use." actions={<Modal title="Add research source" description="Save provenance metadata only. This does not fetch, synchronize, or execute remote content." trigger={<Button variant="primary"><Plus/>Add source</Button>}><ResearchSourceForm onCreate={(source) => saveMutation.mutate(source)} saving={saveMutation.isPending}/></Modal>} />
    {notice ? <Callout title="Research source">{notice}</Callout> : query.isError ? <Callout tone="warning" title="Managed sources unavailable">The sanitized built-in references remain visible.</Callout> : null}
    <Callout title="Secret-safe registry">These rows are sanitized source definitions, not synchronized caches. No external repository has been downloaded by this UI.</Callout>
    <div className="source-grid">{sources.map((source) => <Panel className="source-card" key={source.id}><header><span className="source-icon"><Archive/></span><div><h2>{source.name}</h2><p>{source.kind}</p></div><Badge tone={source.status === "draft" ? "warning" : "neutral"}>{sentence(source.status)}</Badge></header><DataList items={[{ label: "Source ID", value: <code>{source.id}</code> }, { label: "Version / commit", value: "Not pinned" }, { label: "Retrieved", value: "Never" }, { label: "License", value: source.license }, { label: "Use", value: "Comparative reference" }]} /><footer>{source.url ? <a href={source.url} target="_blank" rel="noreferrer">Open official source <ExternalLink/></a> : <span>URL required</span>}<Button size="small" disabled title="No synchronization adapter is configured">Sync</Button></footer></Panel>)}</div>
  </div>;
}

function ResearchSourceForm({ onCreate, saving }: { onCreate: (source: { id: string; name: string; kind: string; url: string; license: string }) => void; saving: boolean }) {
  const [id, setId] = useState("research.local-source.v1"); const [name, setName] = useState("Local research source"); const [url, setUrl] = useState(""); const [license, setLicense] = useState("Review required");
  return <form className="dialog-form" onSubmit={(event) => { event.preventDefault(); onCreate({ id, name, kind: "Comparative reference", url, license }); }}><Field label="Source ID"><input value={id} onChange={(event) => setId(event.target.value)} pattern="[a-z][a-z0-9._-]+" required/></Field><Field label="Display name"><input value={name} onChange={(event) => setName(event.target.value)} required/></Field><Field label="Official URL"><input type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.org/project" required/></Field><Field label="License"><input value={license} onChange={(event) => setLicense(event.target.value)} required/></Field><div className="dialog-actions"><Dialog.Close asChild><Button type="button" variant="ghost">Cancel</Button></Dialog.Close><Dialog.Close asChild><Button type="button" onClick={(event) => { const form = event.currentTarget.form; if (!form?.reportValidity()) { event.preventDefault(); return; } form.requestSubmit(); }} variant="primary" disabled={saving}>{saving ? "Saving" : "Save source draft"}</Button></Dialog.Close></div></form>;
}
