import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, GitCompareArrows, RotateCcw, Search, ShieldAlert, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { api, buildReplayPayload } from "../lib/api";
import type { AutonomyLevel, ComparisonResponse, PreflightReport, RunConfiguration, RunRecord, Scenario } from "../types";
import { Badge, Button, Callout, DataList, EmptyState, ErrorState, Field, LoadingState, PageHeader, Panel, PanelHeader, formatDate, sentence } from "../components/Primitives";

type ReplayStrategy = "exact" | "from_node" | "swap" | "parameters";

export function ComparePage() {
  const runsQuery = useQuery({ queryKey: ["runs"], queryFn: api.runs }); const catalogQuery = useQuery({ queryKey: ["catalog"], queryFn: api.catalog }); const client = useQueryClient();
  const [selected, setSelected] = useState<string[]>([]); const [search, setSearch] = useState(""); const [comparison, setComparison] = useState<ComparisonResponse>(); const [sourceId, setSourceId] = useState(""); const [strategy, setStrategy] = useState<ReplayStrategy>("exact");
  const [fromStep, setFromStep] = useState(""); const [swapStep, setSwapStep] = useState(""); const [swapBehavior, setSwapBehavior] = useState(""); const [profile, setProfile] = useState(""); const [autonomy, setAutonomy] = useState<"preserve" | AutonomyLevel>("preserve"); const [provider, setProvider] = useState(""); const [defenseChange, setDefenseChange] = useState(""); const [parameterJson, setParameterJson] = useState('{\n  "place_fixture": { "record_count": 3 }\n}'); const [targetScope, setTargetScope] = useState("");
  const [replayPreflight, setReplayPreflight] = useState<PreflightReport>(); const [replayConfirmed, setReplayConfirmed] = useState(false); const [approvedBy, setApprovedBy] = useState(""); const [localError, setLocalError] = useState<string>();
  const detailQuery = useQuery({ queryKey: ["run", sourceId], queryFn: () => api.runDetail(sourceId), enabled: Boolean(sourceId) }); const compareMutation = useMutation({ mutationFn: () => api.compare(selected), onSuccess: setComparison }); const source = detailQuery.data ?? runsQuery.data?.runs.find((run) => run.run_id === sourceId);
  const resetReview = () => { setReplayPreflight(undefined); setReplayConfirmed(false); setApprovedBy(""); setLocalError(undefined); };
  useEffect(() => { if (!detailQuery.data || detailQuery.data.mode !== "execute") return; const refs = executionScope(detailQuery.data); setTargetScope(refs.join(", ")); resetReview(); }, [detailQuery.data]);
  const parameterOverrides = useMemo(() => { if (strategy !== "parameters") return {}; try { return parseParameterOverrides(parameterJson, source?.scenario); } catch { return {}; } }, [parameterJson, source?.scenario, strategy]);
  const replayScenario = useMemo(() => source?.scenario ? prepareReplayScenario(source.scenario, strategy, swapStep, swapBehavior, parameterOverrides) : undefined, [parameterOverrides, source?.scenario, strategy, swapBehavior, swapStep]);
  const actionImplementations = resolvedActions(source, strategy === "swap" ? swapStep : undefined);
  const variantReady = strategy === "exact" || (strategy === "from_node" ? Boolean(fromStep) : strategy === "swap" ? Boolean(swapStep && swapBehavior) : Object.keys(parameterOverrides).length > 0);
  const effectiveAutonomy = autonomy === "preserve" ? source?.autonomy ?? source?.autonomy_level ?? "off" : autonomy; const effectiveProvider = provider || providerId(source) || catalogQuery.data?.ai.active_provider || "deterministic-offline.v1"; const effectiveProfile = profile || source?.runner_profile_id || ""; const scopeRefs = targetScope.split(",").map((item) => item.trim()).filter(Boolean);
  const replayConfig: RunConfiguration | undefined = replayScenario ? { mode: source?.mode ?? "simulate", autonomy: effectiveAutonomy, provider: effectiveProvider, model: "", endpoint: "", profileId: effectiveProfile, runnerIds: [], scopeRefs, safetyTier: "controlled", approvalPolicy: "profile", approved: false, approvedBy: "", maxSeconds: 120, maxSteps: 25, maxBytes: 10_485_760, collectors: [], detectionBackends: [], cleanupPolicy: "always", counterfactual: "disabled", fixtureMode: false, actionImplementations } : undefined;
  const preflightMutation = useMutation({ mutationFn: async () => { if (!replayScenario || !replayConfig) throw new Error("The immutable source scenario is unavailable."); assertReplayVariant(strategy, fromStep, swapStep, swapBehavior); if (!scopeRefs.length) throw new Error("Execute replay requires an exact target scope."); if (strategy === "parameters") parseParameterOverrides(parameterJson, source?.scenario); return api.preflight(replayScenario, replayConfig); }, onSuccess: (report) => { setReplayPreflight(report); setReplayConfirmed(false); setApprovedBy(""); setLocalError(undefined); }, onError: (error) => { setReplayPreflight(undefined); setLocalError(error instanceof Error ? error.message : "Replay preflight failed."); } });
  const replayMutation = useMutation({ mutationFn: async () => { if (!source) throw new Error("Select a source run."); assertReplayVariant(strategy, fromStep, swapStep, swapBehavior); const overrides = strategy === "parameters" ? parseParameterOverrides(parameterJson, source.scenario) : undefined; const execute = source.mode === "execute"; if (execute && (!replayConfirmed || !approvedBy.trim() || !scopeRefs.length || !executeReviewReady(replayPreflight))) throw new Error("Execute replay requires the displayed prospective review and a fresh explicit approval."); return api.replay(source.run_id, buildReplayPayload({ strategy, fromStep, swapStep, swapBehavior, profile, autonomy, provider, defenseChange, parameterOverrides: overrides, targetScope: execute ? scopeRefs : undefined, approval: execute ? { confirmed: true, approved_by: approvedBy.trim() } : undefined, actionImplementations: execute && strategy !== "exact" ? actionImplementations : undefined })); }, onSuccess: (run) => { client.invalidateQueries({ queryKey: ["runs"] }); setLocalError(undefined); setReplayPreflight(undefined); setReplayConfirmed(false); setApprovedBy(""); return run; }, onError: (error) => setLocalError(error instanceof Error ? error.message : "Replay was refused."), onSettled: () => { setReplayConfirmed(false); setApprovedBy(""); } });
  if (runsQuery.isPending || catalogQuery.isPending) return <LoadingState label="Loading replay history" />;
  if (runsQuery.isError) return <ErrorState error={runsQuery.error} retry={() => runsQuery.refetch()} />;
  if (catalogQuery.isError) return <ErrorState error={catalogQuery.error} retry={() => catalogQuery.refetch()} />;
  const runs = runsQuery.data.runs.filter((run) => `${run.run_id} ${run.objective ?? ""} ${run.scenario_id ?? ""}`.toLowerCase().includes(search.toLowerCase())); const sourceSteps = source?.steps ?? []; const selectedSwapBehavior = sourceSteps.find((step) => step.step_id === swapStep)?.behavior_id; const sourceBehavior = catalogQuery.data.behaviors.find((item) => item.id === selectedSwapBehavior); const compatible = catalogQuery.data.behaviors.filter((candidate) => sourceBehavior && candidate.id !== sourceBehavior.id && JSON.stringify(candidate.inputs.map((item) => [item.type, item.required, item.multiple])) === JSON.stringify(sourceBehavior.inputs.map((item) => [item.type, item.required, item.multiple])) && JSON.stringify(candidate.outputs.map((item) => [item.type, item.multiple])) === JSON.stringify(sourceBehavior.outputs.map((item) => [item.type, item.multiple])));
  const execute = source?.mode === "execute"; const reviewReady = executeReviewReady(replayPreflight);
  return <div className="page compare-page"><PageHeader eyebrow="Replay & compare" title="Measure what changed" description="Create immutable lineage-linked replays, including strict parameter variants and freshly reviewed Execute replays, then compare canonical outcomes." actions={<Button variant="secondary" onClick={() => runsQuery.refetch()}><RotateCcw/>Refresh history</Button>} />
    {runsQuery.data.unavailable_run_count ? <Callout tone="warning" title="Unavailable run records excluded">{runsQuery.data.unavailable_run_count} in-flight, interrupted, or integrity-failed run record{runsQuery.data.unavailable_run_count === 1 ? " is" : "s are"} unavailable for replay and comparison. Refresh after finalization or recovery completes.</Callout> : null}
    <div className="compare-top-grid"><Panel className="history-panel"><PanelHeader eyebrow="Run history" title="Select a cohort" actions={<Badge>{selected.length} selected</Badge>} /><div className="history-search"><Search/><input aria-label="Search run history" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search run or objective"/></div><div className="run-select-list">{runs.map((run) => <label key={run.run_id}><input type="checkbox" checked={selected.includes(run.run_id)} onChange={(event) => setSelected((items) => event.target.checked ? [...items, run.run_id] : items.filter((id) => id !== run.run_id))}/><span><strong>{run.objective ?? run.scenario_id ?? "Experiment"}</strong><code title={run.run_id}>{shortId(run.run_id)}</code><small>{formatDate(run.created_at)} · {run.steps.length} nodes</small></span><span><Badge tone={run.mode === "execute" ? "warning" : "info"}>{sentence(run.mode)}</Badge><Badge tone={run.status === "completed" ? "success" : "neutral"} dot>{sentence(run.status)}</Badge></span></label>)}</div>{!runs.length ? <EmptyState title="No run records" description="Complete a Simulate run to create a canonical baseline." /> : null}<footer><Button variant="primary" onClick={() => compareMutation.mutate()} disabled={selected.length < 2 || compareMutation.isPending}><GitCompareArrows/>{compareMutation.isPending ? "Comparing" : "Compare selected"}</Button></footer></Panel>
      <Panel className="replay-panel"><PanelHeader eyebrow="Immutable lineage" title="Replay experiment" detail="The source bundle never changes; the result receives a new run ID." /><div className="replay-body"><Field label="Source run"><select value={sourceId} onChange={(event) => { setSourceId(event.target.value); setFromStep(""); setSwapStep(""); setSwapBehavior(""); setProfile(""); setAutonomy("preserve"); setProvider(""); setTargetScope(""); resetReview(); }}><option value="">Select a canonical run</option>{runs.map((run) => <option value={run.run_id} key={run.run_id}>{run.objective ?? run.scenario_id ?? "Experiment"} · {shortId(run.run_id)} · {sentence(run.mode)}</option>)}</select></Field>{detailQuery.isPending ? <LoadingState label="Loading immutable source bundle"/> : null}<fieldset><legend>Replay strategy</legend><div className="choice-grid two replay-choices">{(["exact", "from_node", "swap", "parameters"] as const).map((item) => <label key={item}><input type="radio" name="replay-strategy" checked={strategy === item} onChange={() => { setStrategy(item); resetReview(); }}/><span><strong>{item === "swap" ? "Compatible substitution" : sentence(item)}</strong><small>{item === "exact" ? "Preserve declared inputs" : item === "from_node" ? "Restart from an explicit node" : item === "swap" ? "Replace one typed contract" : "Strict step-to-parameter JSON"}</small></span></label>)}</div></fieldset>
        <div className="config-grid"><Field label="Restart node"><select value={fromStep} onChange={(event) => { setFromStep(event.target.value); resetReview(); }} disabled={strategy !== "from_node"}><option value="">Select node</option>{sourceSteps.map((step) => <option key={step.step_id}>{step.step_id}</option>)}</select></Field><Field label="Substitute node"><select value={swapStep} onChange={(event) => { setSwapStep(event.target.value); setSwapBehavior(""); resetReview(); }} disabled={strategy !== "swap"}><option value="">Select node</option>{sourceSteps.map((step) => <option key={step.step_id}>{step.step_id}</option>)}</select></Field><Field label="Compatible behavior"><select value={swapBehavior} onChange={(event) => { setSwapBehavior(event.target.value); resetReview(); }} disabled={strategy !== "swap" || !swapStep}><option value="">Select compatible behavior</option>{compatible.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></Field><Field label="Profile override"><select value={profile} onChange={(event) => { setProfile(event.target.value); resetReview(); }} disabled={strategy === "exact"}><option value="">Preserve original</option>{catalogQuery.data.runner_profiles.map((item) => <option key={item.id}>{item.id}</option>)}</select></Field><Field label="AI autonomy override"><select value={autonomy} onChange={(event) => { setAutonomy(event.target.value as typeof autonomy); resetReview(); }} disabled={strategy === "exact"}><option value="preserve">Preserve original</option><option value="off">Off</option><option value="assist">Assist</option><option value="auto">Auto</option></select></Field><Field label="AI provider override"><select value={provider} onChange={(event) => { setProvider(event.target.value); resetReview(); }} disabled={strategy === "exact"}><option value="">Preserve original</option>{(catalogQuery.data.ai.providers ?? []).map((item) => <option value={item.provider_id} key={item.provider_id}>{item.provider_id}</option>)}</select></Field></div>
        {strategy === "parameters" ? <Field label="Parameter overrides JSON" hint='Strict object: {"step_id":{"parameter":value}}. Unknown steps/parameters and invalid types are refused by replay validation.'><textarea rows={8} value={parameterJson} onChange={(event) => { setParameterJson(event.target.value); resetReview(); }} spellCheck={false}/></Field> : null}<Field label="Declared defense change" hint={strategy === "exact" ? "Exact replay cannot include variant metadata." : "Recorded in immutable replay lineage; BlueFire does not deploy a defense change."}><textarea rows={3} maxLength={500} value={defenseChange} onChange={(event) => { setDefenseChange(event.target.value); resetReview(); }} placeholder="Describe the externally applied or modeled defense change" disabled={strategy === "exact"}/></Field>
        {execute ? <><Callout tone="warning" title="Execute replay is a new effect authorization">The original approval is never reused. This check previews the resulting base scenario, scope, profile, actions, alternates, and cleanup; it is not the replay-specific lineage binding. The synchronous replay endpoint reconstructs that binding, re-runs policy and preflight, and atomically consumes a fresh one-time approval or refuses the request.</Callout><Field label="Exact target scope"><input value={targetScope} onChange={(event) => { setTargetScope(event.target.value); resetReview(); }} placeholder="sandbox.workspace"/></Field><Button variant="secondary" onClick={() => preflightMutation.mutate()} disabled={!replayScenario || !variantReady || preflightMutation.isPending || !scopeRefs.length}><ShieldCheck/>{preflightMutation.isPending ? "Resolving prospective check" : "Run prospective base-plan check"}</Button>{replayPreflight ? <ReplayPreflight report={replayPreflight}/> : null}<label className="check-row"><input type="checkbox" checked={replayConfirmed} onChange={(event) => setReplayConfirmed(event.target.checked)} disabled={!reviewReady}/><span><strong>I approve this reviewed Execute replay request once</strong><small>Unchecked by default; the server derives the exact replay binding and clears/refuses any mismatch</small></span></label><Field label="Fresh replay operator identity"><input value={approvedBy} onChange={(event) => setApprovedBy(event.target.value)} disabled={!reviewReady} autoComplete="off" maxLength={128}/></Field></> : null}
        {!variantReady && sourceId ? <Callout tone="warning" title="Replay variant incomplete">{strategy === "from_node" ? "Choose a restart node." : strategy === "swap" ? "Choose both a source node and compatible behavior." : "Supply at least one valid step parameter override."}</Callout> : null}{localError ? <Callout tone="danger" title="Replay refused">{localError}</Callout> : replayMutation.isSuccess ? <Callout tone="success" title="Replay created"><code>{replayMutation.data.run_id}</code> is lineage-linked to <code>{sourceId}</code>.</Callout> : null}<Button variant="primary" className="button-full" onClick={() => replayMutation.mutate()} disabled={!sourceId || !variantReady || replayMutation.isPending || Boolean(execute && (!reviewReady || !replayConfirmed || !approvedBy.trim()))}>{replayMutation.isPending ? "Creating immutable replay" : execute ? "Create approved Execute replay" : "Create Simulate replay"}</Button></div></Panel>
    </div>
    {compareMutation.isError ? <ErrorState title="Comparison unavailable" error={compareMutation.error} /> : comparison ? <ComparisonResult comparison={comparison} /> : <Panel><EmptyState icon={<GitCompareArrows/>} title="Select at least two runs" description="The first selected run becomes the baseline. Canonical deltas will appear here." /></Panel>}
  </div>;
}

function ReplayPreflight({ report }: { report: PreflightReport }) {
  const binding = report.approval_binding; const envelope = report.approval_envelope; const steps = Array.isArray(report.plan?.steps) ? report.plan.steps.filter((item): item is Record<string, unknown> => Boolean(item) && typeof item === "object") : [];
  return <section className={`preflight-result ${executeReviewReady(report) ? "approval-required" : "blocked"}`} aria-label="Prospective Execute replay check"><header><strong>{executeReviewReady(report) ? "Prospective base plan ready for review" : "Prospective check blocked"}</strong><Badge tone={executeReviewReady(report) ? "warning" : "danger"}>{sentence(report.status)}</Badge></header><Callout title="Not the replay binding">These digests cover this prospective base-plan compilation. Replay lineage, restart position, and source identity are bound only inside the replay request and may change or refuse the final authorization.</Callout><DataList items={[{ label: "Prospective state digest", value: binding ? <code>{binding.state_digest}</code> : "Not reported" }, { label: "Prospective plan digest", value: binding ? <code>{binding.plan_digest}</code> : "Not reported" }, { label: "Prospective scope digest", value: binding ? <code>{binding.target_scope_digest}</code> : "Not reported" }, { label: "Prospective envelope digest", value: envelope ? <code>{envelope.envelope_digest}</code> : "Not reported" }, { label: "Profile / tier", value: binding ? `${binding.profile_id} / ${sentence(binding.maximum_tier)}` : "Not reported" }, { label: "Cleanup", value: JSON.stringify(report.cleanup ?? {}) }]} />{steps.map((step) => <article className="replay-plan-step" key={String(step.step_id)}><strong>{String(step.step_id)}</strong><code>{String(step.behavior_id)}</code><Badge tone={step.action_id ? "warning" : "info"}>{String(step.action_id ?? step.simulation_id ?? "Unresolved")}</Badge><pre>{JSON.stringify(step.parameters ?? {}, null, 2)}</pre></article>)}{envelope ? <p className="field-note">{envelope.steps.reduce((count, step) => count + step.options.length, 0)} primary/alternate contract options appear in this prospective compilation.</p> : null}{report.findings?.length ? <ul>{report.findings.map((item, index) => <li key={index}>{typeof item === "string" ? item : item.message ?? item.code ?? "Finding"}</li>)}</ul> : null}</section>;
}

function executeReviewReady(report?: PreflightReport) { return Boolean(report && report.status === "approval_required" && report.plan && report.approval_binding && report.approval_envelope); }

function assertReplayVariant(strategy: ReplayStrategy, fromStep: string, swapStep: string, swapBehavior: string): void {
  if (strategy === "from_node" && !fromStep) throw new Error("Choose a restart node for a from-node replay.");
  if (strategy === "swap" && (!swapStep || !swapBehavior)) throw new Error("Choose both a source node and compatible behavior for substitution.");
}

function prepareReplayScenario(source: Scenario, strategy: ReplayStrategy, swapStep: string, swapBehavior: string, overrides: Record<string, Record<string, unknown>>): Scenario {
  return { ...source, steps: source.steps.map((step) => ({ ...step, behavior_id: strategy === "swap" && step.id === swapStep && swapBehavior ? swapBehavior : step.behavior_id, parameters: strategy === "parameters" && overrides[step.id] ? { ...step.parameters, ...overrides[step.id] } : { ...step.parameters } })) };
}

export function parseParameterOverrides(value: string, scenario?: Scenario): Record<string, Record<string, unknown>> {
  if (value.length > 100_000) throw new Error("Parameter override JSON is too large."); const parsed: unknown = JSON.parse(value); if (!isPlainObject(parsed)) throw new Error("Parameter overrides must be a JSON object."); const entries = Object.entries(parsed); if (!entries.length || entries.length > 100) throw new Error("Supply between 1 and 100 step override objects."); const knownSteps = new Set(scenario?.steps.map((step) => step.id) ?? []); const result: Record<string, Record<string, unknown>> = {};
  for (const [stepId, parameters] of entries) { if (["__proto__", "prototype", "constructor"].includes(stepId) || !isPlainObject(parameters)) throw new Error("Each step must map to a plain parameter object."); if (scenario && !knownSteps.has(stepId)) throw new Error(`Unknown replay step: ${stepId}`); assertSafeJson(parameters); result[stepId] = parameters; }
  return result;
}

function isPlainObject(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === "object" && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype; }
function assertSafeJson(value: unknown): void { if (Array.isArray(value)) { value.forEach(assertSafeJson); return; } if (!value || typeof value !== "object") return; for (const [key, child] of Object.entries(value as Record<string, unknown>)) { if (["__proto__", "prototype", "constructor"].includes(key)) throw new Error("Reserved object keys are not allowed."); assertSafeJson(child); } }
function providerId(source?: RunRecord) { return typeof source?.ai_provider === "string" ? source.ai_provider : source?.ai_provider && typeof source.ai_provider.provider_id === "string" ? source.ai_provider.provider_id : undefined; }
function executionScope(source: RunRecord) { const explicit = source.target_scope?.scope_refs; if (Array.isArray(explicit)) return explicit.filter((item): item is string => typeof item === "string"); const policyScope = source.policy?.authorized_target_scope; if (policyScope && typeof policyScope === "object" && Array.isArray((policyScope as Record<string, unknown>).scope_refs)) return ((policyScope as Record<string, unknown>).scope_refs as unknown[]).filter((item): item is string => typeof item === "string"); const profileScope = source.profile?.scope; return Array.isArray(profileScope) ? profileScope.filter((item): item is string => typeof item === "string") : []; }
function resolvedActions(source?: RunRecord, omittedStep?: string) { const steps = Array.isArray(source?.plan?.steps) ? source.plan.steps : []; return Object.fromEntries(steps.filter((item): item is Record<string, unknown> => Boolean(item) && typeof item === "object" && typeof item.step_id === "string" && typeof item.action_id === "string" && item.step_id !== omittedStep).map((item) => [String(item.step_id), String(item.action_id)])); }

export function ComparisonResult({ comparison }: { comparison: ComparisonResponse }) {
  const baseline = comparison.summaries.find((item) => item.run_id === comparison.baseline_run_id) ?? comparison.summaries[0];
  const changed = comparison.deltas.filter(hasMaterialDelta).length;
  return <div className="comparison-results">
    <div className="stat-grid">
      <article className="stat stat-info"><span>Baseline</span><strong><Link to={runReviewPath(comparison.baseline_run_id)} aria-label="Review baseline run summary"><code title={comparison.baseline_run_id}>{shortId(comparison.baseline_run_id)}</code></Link></strong><small>{baseline?.path.length ?? 0} path nodes</small></article>
      <article className="stat stat-info"><span>Cohort</span><strong>{comparison.run_ids.length}</strong><small>Canonical run records</small></article>
      <article className={`stat ${changed ? "stat-warning" : "stat-success"}`}><span>Material deltas</span><strong>{changed}</strong><small>{changed ? "Inspect assessments below" : "No material delta reported"}</small></article>
      <article className="stat stat-success"><span>Comparison ID</span><strong><code title={comparison.comparison_id}>{shortId(comparison.comparison_id)}</code></strong><small>Content-derived record</small></article>
    </div>
    <Panel><PanelHeader eyebrow="Path overlay" title="Side-by-side execution lanes" detail="Human-readable outcomes come first; each run links back to its canonical review."/><div className="compare-lanes">{comparison.summaries.map((summary, laneIndex) => <article key={summary.run_id}>
      <header><Badge tone={laneIndex === 0 ? "info" : "neutral"}>{laneIndex === 0 ? "Baseline" : `Variant ${laneIndex}`}</Badge><Link to={runReviewPath(summary.run_id)} aria-label={`Review ${laneIndex === 0 ? "baseline" : `variant ${laneIndex}`} execution lane`}><code title={summary.run_id}>{shortId(summary.run_id)}</code></Link></header>
      <ol>{summary.path.map((step, index) => <li key={`${step}-${index}`} data-status={summary.outcomes[step] === "success" ? "succeeded" : summary.outcomes[step]}><span>{String(index + 1).padStart(2, "0")}</span><strong>{step}</strong><small>{sentence(summary.outcomes[step] ?? "unknown")}</small></li>)}</ol>
      <DataList items={[
        { label: "Mode / profile", value: `${sentence(summary.mode ?? "not_reported")} / ${summary.profile_id ?? "Not reported"}` },
        { label: "Objective", value: summary.objective_reached === true ? "Reached" : summary.objective_reached === false ? "Prevented / incomplete" : "Not reported" },
        { label: "First block", value: summary.first_blocked_step ?? "None recorded" },
        { label: "Cleanup", value: summary.cleanup_success === true ? "Reconciled" : summary.cleanup_success === false ? "Outstanding" : "Not reported" },
        { label: "Duration", value: formatDuration(summary.duration_ms) },
        { label: "Outcomes", value: formatCountMap(summary.outcome_counts ?? countValues(Object.values(summary.outcomes)), "None reported") },
        { label: "Evidence provenance", value: formatCountMap(summary.evidence_provenance, "None reported") },
        { label: "Detection lifecycle", value: formatCountMap(summary.detection_states, "None reported") },
        { label: "Detection matches", value: formatReportedCount(summary.detection_matches) },
        { label: "Benign matches", value: formatReportedCount(summary.benign_matches) },
        { label: "Policy decisions", value: formatCountMap(summary.policy_states, "None reported") },
        { label: "Telemetry", value: formatList(summary.telemetry) },
        { label: "Controls", value: formatList(summary.controls) },
        { label: "AI autonomy", value: summary.autonomy ? sentence(summary.autonomy) : "Not reported" },
        { label: "AI provider", value: summary.ai_provider_id ?? "None reported" },
        { label: "AI proposals", value: `${formatReportedCount(summary.ai_proposal_count)} · ${formatCountMap(summary.ai_applications, "No applications reported")}` },
        { label: "Remaining budgets", value: formatCountMap(summary.remaining_budgets, "None reported") },
        { label: "Counterfactual path", value: formatList(summary.counterfactual_steps, "None recorded") },
      ]} />
    </article>)}</div></Panel>
    <div className="delta-grid">{comparison.deltas.map((delta) => {
      const assessment = delta.assessment ?? (hasMaterialDelta(delta) ? "material_change" : "no_material_change");
      const noPathDivergence = delta.first_path_divergence === null || delta.first_path_divergence === undefined || delta.first_path_divergence < 0;
      return <Panel key={delta.to_run_id}><PanelHeader eyebrow="Delta assessment" title={`${shortId(delta.from_run_id)} → ${shortId(delta.to_run_id)}`} detail={`${sentence(assessment)} · ${formatList(delta.signals, "No assessment signals")}`} actions={<Badge tone={assessmentTone(assessment)}>{sentence(assessment)}</Badge>} />
        <div className="delta-summary"><div><span>{noPathDivergence ? <CheckCircle2/> : <ShieldAlert/>}</span><strong>Path divergence</strong><small>{noPathDivergence ? "No divergence" : `Node index ${delta.first_path_divergence! + 1}`}</small></div><div><span>{delta.objective_changed ? <ShieldAlert/> : <CheckCircle2/>}</span><strong>Objective</strong><small>{formatChanged(delta.objective_changed)}</small></div><div><span>{delta.first_blocked_changed ? <ShieldAlert/> : <CheckCircle2/>}</span><strong>First prevention</strong><small>{formatChanged(delta.first_blocked_changed)}</small></div><div><span>{delta.cleanup_changed ? <ShieldAlert/> : <CheckCircle2/>}</span><strong>Cleanup</strong><small>{formatChanged(delta.cleanup_changed)}</small></div></div>
        <div className="delta-columns">
          <div><h3>Evidence, detections & outcomes</h3><DataList items={[
            { label: "Evidence delta", value: formatDeltaMap(delta.evidence_delta) },
            { label: "Detection lifecycle delta", value: formatDeltaMap(delta.detection_delta) },
            { label: "Detection match delta", value: formatSignedNumber(delta.detection_match_delta) },
            { label: "Benign match delta", value: formatSignedNumber(delta.benign_match_delta) },
            { label: "Outcome delta", value: formatDeltaMap(delta.outcome_delta) },
          ]} /></div>
          <div><h3>Policy, AI & runtime</h3><DataList items={[
            { label: "Assessment", value: sentence(assessment) },
            { label: "Signals", value: formatList(delta.signals, "No material signals") },
            { label: "Autonomy", value: formatChanged(delta.autonomy_changed) },
            { label: "AI provider", value: formatChanged(delta.ai_provider_changed) },
            { label: "AI proposal delta", value: formatSignedNumber(delta.ai_proposal_delta) },
            { label: "Duration delta", value: formatDurationDelta(delta.duration_delta_ms) },
          ]} /></div>
          <div><h3>Telemetry & controls</h3><DataList items={[
            { label: "Telemetry added", value: formatList(delta.telemetry_added) },
            { label: "Telemetry removed", value: formatList(delta.telemetry_removed) },
            { label: "Controls added", value: formatList(delta.controls_added) },
            { label: "Controls removed", value: formatList(delta.controls_removed) },
          ]} /></div>
        </div>
        <details><summary>Show technical comparison delta</summary><pre aria-label={`Technical comparison delta ${delta.to_run_id}`}>{JSON.stringify(delta, null, 2)}</pre></details>
      </Panel>;
    })}</div>
  </div>;
}

type ComparisonDeltaItem = ComparisonResponse["deltas"][number];

function hasMaterialDelta(delta: ComparisonDeltaItem) {
  if (delta.assessment) return delta.assessment !== "no_material_change";
  return Boolean(delta.objective_changed || delta.first_blocked_changed || delta.cleanup_changed || delta.autonomy_changed || delta.ai_provider_changed || delta.first_path_divergence !== null && delta.first_path_divergence !== undefined && delta.first_path_divergence >= 0 || Object.values(delta.evidence_delta ?? {}).some(Boolean) || Object.values(delta.detection_delta ?? {}).some(Boolean) || Object.values(delta.outcome_delta ?? {}).some(Boolean) || delta.detection_match_delta || delta.benign_match_delta || delta.ai_proposal_delta || delta.duration_delta_ms || delta.telemetry_added?.length || delta.telemetry_removed?.length || delta.controls_added?.length || delta.controls_removed?.length);
}

function assessmentTone(value: string): "neutral" | "success" | "warning" | "danger" {
  return value === "improved" ? "success" : value === "regressed" ? "danger" : value === "no_material_change" ? "neutral" : "warning";
}

function formatChanged(value?: boolean) { return value === undefined ? "Not reported" : value ? "Changed" : "Stable"; }
function formatReportedCount(value?: number) { return value === undefined ? "Not reported" : new Intl.NumberFormat().format(value); }
function formatList(values?: string[], empty = "None") { return values?.length ? values.map(sentence).join(", ") : empty; }
function countValues(values: string[]) { return values.reduce<Record<string, number>>((counts, value) => { counts[value] = (counts[value] ?? 0) + 1; return counts; }, {}); }
function formatCountMap(values?: Record<string, number>, empty = "None") { return values && Object.keys(values).length ? Object.entries(values).map(([key, value]) => `${sentence(key)}: ${new Intl.NumberFormat().format(value)}`).join(", ") : empty; }
function formatDeltaMap(values?: Record<string, number>) { return values && Object.keys(values).length ? Object.entries(values).map(([key, value]) => `${sentence(key)} ${value >= 0 ? "+" : ""}${value}`).join(", ") : "No delta"; }
function formatSignedNumber(value?: number) { return value === undefined ? "Not reported" : value === 0 ? "No delta" : `${value > 0 ? "+" : ""}${new Intl.NumberFormat().format(value)}`; }
function formatDuration(value?: number | null) { if (value === undefined || value === null) return "Not reported"; return formatMilliseconds(value); }
function formatDurationDelta(value?: number | null) { if (value === undefined || value === null) return "Not comparable"; return value === 0 ? "No delta" : `${value > 0 ? "+" : "−"}${formatMilliseconds(Math.abs(value))}`; }
function formatMilliseconds(value: number) { return Math.abs(value) < 1_000 ? `${new Intl.NumberFormat().format(value)} ms` : `${(value / 1_000).toLocaleString(undefined, { maximumFractionDigits: 2 })} s`; }
function runReviewPath(runId: string) { return `/runs/${encodeURIComponent(runId)}`; }
function shortId(value: string) { return value.length > 22 ? `${value.slice(0, 10)}…${value.slice(-8)}` : value; }
