import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, AlertTriangle, CheckCircle2, CircleStop, Clock3, FileSearch, Gauge, ListTree, Pause, Play, RotateCcw, ShieldCheck, Sparkles, TerminalSquare } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { api, DEMO_MODE } from "../lib/api";
import { ExecuteOnboarding, GUIDED_EXECUTE_PROFILE_ID, GUIDED_EXECUTE_SCENARIO_ID, guidedExecuteConfiguration } from "../components/ExecuteOnboarding";
import { ProposalReviewWorkspace } from "../components/ProposalReview";
import { useProduct } from "../state/ProductContext";
import type { AIProposalDecisionResult, AIProposalReview, ApprovalBinding, ApprovalEnvelope, AutonomyLevel, CatalogResponse, PreflightReport, RunConfiguration, RunEventPage, RunJob, RunRecord, RunStep, Scenario } from "../types";
import { Badge, Button, Callout, DataList, ErrorState, Field, LoadingState, PageHeader, Panel, PanelHeader, Stat, formatDate, sentence } from "../components/Primitives";

const terminalJobStates = new Set<RunJob["state"]>(["cancelled", "completed", "failed", "interrupted"]);
const approvalBindingFields = ["state_digest", "plan_digest", "target_scope_digest", "profile_id", "maximum_tier"] as const;

interface RunPreflightAttempt {
  generation: number;
  scenario: Scenario;
  config: RunConfiguration;
}

export function RunsPage() {
  const { runId } = useParams<{ runId?: string }>();
  const navigate = useNavigate();
  const catalog = useQuery({ queryKey: ["catalog"], queryFn: api.catalog });
  const runsQuery = useQuery({ queryKey: ["runs"], queryFn: api.runs });
  const scenariosQuery = useQuery({ queryKey: ["scenarios"], queryFn: api.scenarios });
  const runnerLifecycleQuery = useQuery({ queryKey: ["runner-lifecycle"], queryFn: api.runnerStatus });
  const historicalRunQuery = useQuery({ queryKey: ["run", runId], queryFn: () => api.runDetail(runId!), enabled: Boolean(runId) });
  const { scenario, setScenario, dirty, runConfig, setRunConfig, clearApproval, activeRun, setActiveRun } = useProduct();
  const queryClient = useQueryClient();
  const [preflight, setPreflight] = useState<PreflightReport>(); const [notice, setNotice] = useState<string>();
  const [activeJob, setActiveJob] = useState<RunJob | null>(null); const [jobPreflight, setJobPreflight] = useState<PreflightReport>(); const [approvalRequest, setApprovalRequest] = useState<Record<string, unknown> | null>(null);
  const [activeProposalReview, setActiveProposalReview] = useState<AIProposalReview>();
  const [jobApprovalConfirmed, setJobApprovalConfirmed] = useState(false); const [jobApprovedBy, setJobApprovedBy] = useState("");
  const [liveEvents, setLiveEvents] = useState<RunEventPage["items"]>([]);
  const preflightGeneration = useRef(0);
  const jobQuery = useQuery({ queryKey: ["job", activeJob?.job_id], queryFn: () => api.job(activeJob!.job_id), enabled: Boolean(activeJob && !terminalJobStates.has(activeJob.state)), refetchInterval: (query) => { const state = (query.state.data as RunJob | undefined)?.state; return state && terminalJobStates.has(state) ? false : 750; } });
  const liveRunId = typeof activeJob?.progress.run_id === "string" ? activeJob.progress.run_id : undefined;
  const eventCursor = liveEvents.reduce((maximum, event) => Math.max(maximum, Number(event.sequence) || 0), 0);
  const eventsQuery = useQuery({ queryKey: ["run-events", liveRunId, eventCursor, activeJob?.state], queryFn: () => api.runEvents(liveRunId!, eventCursor), enabled: Boolean(liveRunId), refetchInterval: activeJob && terminalJobStates.has(activeJob.state) ? false : 650 });
  const resultRunId = activeJob?.state === "completed" ? activeJob.result_ref : undefined;
  const resultQuery = useQuery({ queryKey: ["run", resultRunId], queryFn: () => api.runDetail(resultRunId!), enabled: Boolean(resultRunId && activeRun?.run_id !== resultRunId) });
  useEffect(() => { if (jobQuery.data) { setActiveJob(jobQuery.data); if (jobQuery.data.approval_request !== undefined) setApprovalRequest(jobQuery.data.approval_request); } }, [jobQuery.data]);
  useEffect(() => { if (jobQuery.error) setNotice(jobQuery.error instanceof Error ? jobQuery.error.message : "Job status could not be refreshed."); }, [jobQuery.error]);
  useEffect(() => { setLiveEvents([]); }, [activeJob?.job_id]);
  useEffect(() => { if (eventsQuery.data?.items.length) setLiveEvents((current) => { const merged = new Map(current.map((event) => [event.sequence, event])); for (const event of eventsQuery.data.items) merged.set(event.sequence, event); return [...merged.values()].sort((left, right) => left.sequence - right.sequence); }); }, [eventsQuery.data]);
  useEffect(() => { if (eventsQuery.error) setNotice(eventsQuery.error instanceof Error ? eventsQuery.error.message : "Live event polling failed."); }, [eventsQuery.error]);
  useEffect(() => { if (resultQuery.data) { setActiveRun(resultQuery.data); setNotice(`Run ${resultQuery.data.run_id} completed and its canonical record is ready for review.`); queryClient.invalidateQueries({ queryKey: ["runs"] }); } }, [queryClient, resultQuery.data, setActiveRun]);
  useEffect(() => { setJobApprovalConfirmed(false); setJobApprovedBy(""); }, [activeJob?.job_id, activeJob?.progress.approval_kind, activeJob?.progress.approval_request_id, activeJob?.request?.approval_request_id, approvalRequest?.approval_id, approvalRequest?.status, approvalRequest?.state_digest, approvalRequest?.plan_digest, approvalRequest?.target_scope_digest, approvalRequest?.profile_id, approvalRequest?.maximum_tier]);
  const preflightMutation = useMutation({ mutationFn: async (attempt: RunPreflightAttempt) => ({ generation: attempt.generation, report: await api.preflight(attempt.scenario, attempt.config) }), onSuccess: ({ generation, report }) => { if (generation !== preflightGeneration.current) return; setPreflight(report); setNotice(report.ready ? "Preflight resolved the current policy envelope." : report.status === "approval_required" && report.approval_binding && report.approval_envelope ? "Preflight resolved the exact Execute envelope. Review it before creating an approval-gated job." : "Preflight did not authorize this intent."); }, onError: (error, attempt) => { if (attempt.generation !== preflightGeneration.current) return; setPreflight(undefined); setNotice(error instanceof Error ? error.message : "Preflight failed."); }, onSettled: (_result, _error, attempt) => { if (attempt.generation === preflightGeneration.current) clearApproval(); } });
  const requestPreflight = () => { const generation = ++preflightGeneration.current; preflightMutation.mutate({ generation, scenario: structuredClone(scenario), config: structuredClone(runConfig) }); };
  const invalidatePreflight = () => { preflightGeneration.current += 1; setPreflight(undefined); };
  const runMutation = useMutation({ mutationFn: () => api.submitRun(scenario, runConfig), onMutate: () => { setNotice(runConfig.mode === "simulate" ? "Submitting a durable Simulate job." : "Creating a durable Execute job with a separate approval gate."); setActiveRun(null); }, onSuccess: (submission) => { setActiveJob(submission.job); setJobPreflight(submission.preflight ?? undefined); setApprovalRequest(submission.approval_request ?? null); setNotice(`Job ${submission.job.job_id} was accepted in ${sentence(submission.job.state)} state.`); queryClient.invalidateQueries({ queryKey: ["runs"] }); }, onError: (error) => setNotice(error instanceof Error ? error.message : "Job submission was refused."), onSettled: clearApproval });
  const approvalMutation = useMutation({ mutationFn: ({ jobId, approvedBy }: { jobId: string; approvedBy: string }) => api.approveJob(jobId, approvedBy), onSuccess: (result) => { setActiveJob(result.job); setApprovalRequest(result.approval_request ?? null); setNotice(`The exact envelope for ${result.job.job_id} was approved once and released to the job controller.`); }, onError: (error) => setNotice(error instanceof Error ? error.message : "Job approval was refused."), onSettled: () => { setJobApprovalConfirmed(false); setJobApprovedBy(""); clearApproval(); } });
  const runnerLifecycleMutation = useMutation({ mutationFn: (action: "bootstrap" | "start") => action === "bootstrap" ? api.bootstrapRunner(GUIDED_EXECUTE_PROFILE_ID) : api.startRunner(GUIDED_EXECUTE_PROFILE_ID), onSuccess: (status) => { queryClient.setQueryData(["runner-lifecycle"], status); setNotice(status.state === "ready" ? "The packaged runner is authenticated and ready for the guided Execute path." : "The packaged runner and recoverable local trust are verified. Start the authenticated host next."); }, onError: (error) => setNotice(error instanceof Error ? error.message : "The guided runner action was refused.") });
  const controlMutation = useMutation({ mutationFn: ({ jobId, action }: { jobId: string; action: "pause" | "resume" | "cancel" }) => api.controlJob(jobId, action), onSuccess: (job, variables) => { setActiveJob(job); setNotice(`${sentence(variables.action)} was requested for ${job.job_id}; the durable state is ${sentence(job.state)}.`); }, onError: (error) => setNotice(error instanceof Error ? error.message : "Job control request was refused.") });
  const retryMutation = useMutation({ mutationFn: (jobId: string) => api.retryJob(jobId), onSuccess: (result) => { setActiveJob(result.job); setJobPreflight(result.preflight ?? undefined); setApprovalRequest(result.approval_request ?? null); setActiveProposalReview(undefined); setNotice(`Replacement job ${result.job.job_id} was created from interrupted job ${result.retry_of_job_id}. The source remains immutable.`); }, onError: (error) => setNotice(error instanceof Error ? error.message : "The interrupted job could not be retried safely.") });
  const handleProposalDecision = (result: AIProposalDecisionResult, review: AIProposalReview) => { setActiveJob(result.job); setActiveProposalReview(review); setApprovalRequest(result.approval_request ?? null); if (result.job.progress.approval_kind === "ai_proposal_execute") setJobPreflight(undefined); setNotice(result.job.progress.approval_kind === "ai_proposal_execute" ? "The registered proposal was accepted. Execute remains stopped at a new, separately bound one-time approval stage." : `The proposal was ${review.status}; durable job state is ${sentence(result.job.state)}.`); };
  if (catalog.isPending || (runId && historicalRunQuery.isPending)) return <LoadingState label={runId ? "Loading canonical run review" : "Loading run controls"} />;
  if (catalog.isError) return <ErrorState error={catalog.error} retry={() => catalog.refetch()} />;
  if (runId && historicalRunQuery.isError) return <div className="page runs-page"><PageHeader eyebrow="Run history" title="Canonical run unavailable" description="The requested run could not be loaded from durable history." actions={<Link to="/runs"><Button variant="secondary">Back to run workspace</Button></Link>} /><ErrorState error={historicalRunQuery.error} retry={() => historicalRunQuery.refetch()} /></div>;
  if (runId && historicalRunQuery.data) return <HistoricalRunReview run={historicalRunQuery.data} catalog={catalog.data} />;
  const configReady = runConfig.mode === "simulate" || Boolean(runConfig.profileId && runConfig.approved && runConfig.approvedBy.trim());
  const preflightCanAuthorize = Boolean(preflight?.ready || (runConfig.mode === "execute" && preflight?.status === "approval_required" && preflight.approval_binding && preflight.approval_envelope));
  const jobIsActive = Boolean(activeJob && !terminalJobStates.has(activeJob.state));
  const canStart = preflightCanAuthorize && configReady && !runMutation.isPending && !jobIsActive;
  const guidedProfile = catalog.data.runner_profiles.find((profile) => profile.id === GUIDED_EXECUTE_PROFILE_ID);
  const guidedScenario = scenariosQuery.data?.scenarios.find((item) => item.id === GUIDED_EXECUTE_SCENARIO_ID);
  const scrollToGuideTarget = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  const selectGuidedScenario = () => {
    if (!guidedProfile || !guidedScenario) return;
    setScenario(structuredClone(guidedScenario), false);
    setRunConfig(guidedExecuteConfiguration(runConfig, guidedProfile));
    invalidatePreflight();
    setActiveJob(null);
    setJobPreflight(undefined);
    setApprovalRequest(null);
    setActiveProposalReview(undefined);
    setActiveRun(null);
    setJobApprovalConfirmed(false);
    setJobApprovedBy("");
    setNotice("The seeded restricted canary is selected with AI Off, exact sandbox scope, independent filesystem observation, and mandatory cleanup.");
  };

  return <div className="page runs-page">
    <PageHeader eyebrow="Run control" title="Preflight every path. Observe every decision." description="Mode controls effects; AI autonomy is independent. Model proposals, policy authorization, dispatch, evidence, and cleanup stay distinct." actions={<div className="view-toggle" role="tablist" aria-label="Run workspace views"><button role="tab" aria-selected="true">Configure & live</button><button role="tab" aria-selected="false" onClick={() => activeRun && navigate(runReviewPath(activeRun.run_id))} disabled={!activeRun}>Review latest</button></div>} />
    {notice ? <Callout tone={runMutation.isError || approvalMutation.isError || runnerLifecycleMutation.isError || controlMutation.isError || jobQuery.isError || eventsQuery.isError || resultQuery.isError ? "danger" : preflight && !preflight.ready ? "warning" : "info"} title="Control-plane status">{notice}</Callout> : null}
    <>
      <ExecuteOnboarding profile={guidedProfile} seededScenario={guidedScenario} selectedScenario={scenario} config={runConfig} runner={runnerLifecycleQuery.data} runnerPending={runnerLifecycleQuery.isPending} runnerError={runnerLifecycleQuery.error} runnerActionPending={runnerLifecycleMutation.isPending} preflight={preflight} preflightPending={preflightMutation.isPending} job={activeJob} approvalReleased={["consumed", "claimed"].includes(String(approvalRequest?.status ?? ""))} run={activeRun} jobSubmissionPending={runMutation.isPending} canCreateJob={canStart} demoMode={DEMO_MODE} onRunnerAction={(action) => runnerLifecycleMutation.mutate(action)} onSelectScenario={selectGuidedScenario} onPreflight={requestPreflight} onCreateJob={() => runMutation.mutate()} onReviewEnvelope={() => scrollToGuideTarget("execute-envelope-review")} onReviewApproval={() => scrollToGuideTarget("durable-execute-approval")} />
      <div className="run-layout"><RunConfigurationPanel config={runConfig} onChange={(next) => { const intentChanged = JSON.stringify({ ...runConfig, approved: false, approvedBy: "" }) !== JSON.stringify({ ...next, approved: false, approvedBy: "" }); setRunConfig(next); if (intentChanged) invalidatePreflight(); }} catalog={catalog.data} preflight={preflight} /><PlanPreview scenarioTitle={scenario.title} stepIds={scenario.steps.map((step) => step.id)} edgeCount={scenario.edges.length} dirty={dirty} config={runConfig} catalog={catalog.data} preflight={preflight} /></div>
      <div className="run-action-bar"><div>{activeJob ? <Badge tone={statusTone(activeJob.state)} dot>{sentence(activeJob.state)}</Badge> : <Badge tone={preflight?.ready ? "success" : preflight?.status === "approval_required" ? "warning" : preflight ? "danger" : "neutral"} dot>{preflight?.ready ? "Ready" : preflight?.status === "approval_required" ? "Envelope reviewed locally" : preflight ? sentence(preflight.status) : "Preflight required"}</Badge>}<span>{runConfig.mode === "simulate" ? "No external behavior effects" : "Job creation and one-time durable approval remain separate"}</span></div><Button variant="secondary" onClick={requestPreflight} disabled={preflightMutation.isPending || !scenario.steps.length || jobIsActive}>{preflightMutation.isPending ? <Activity className="spin"/> : <ShieldCheck/>}Run preflight</Button><Button variant="primary" onClick={() => runMutation.mutate()} disabled={!canStart}>{runMutation.isPending ? <Activity className="spin"/> : <Play/>}{runMutation.isPending ? "Submitting job" : runConfig.mode === "execute" ? "Create approval-gated job" : "Submit Simulate job"}</Button></div>
      <LiveConsole run={activeRun} job={activeJob} events={liveEvents} pending={runMutation.isPending || Boolean(resultRunId && resultQuery.isPending) || Boolean(activeJob && !terminalJobStates.has(activeJob.state))} config={runConfig} approvalPreflight={jobPreflight} approvalRequest={approvalRequest} proposalReview={activeProposalReview} approvalConfirmed={jobApprovalConfirmed} approvedBy={jobApprovedBy} approvalPending={approvalMutation.isPending} controlPending={controlMutation.isPending || retryMutation.isPending} onApprovalConfirmed={setJobApprovalConfirmed} onApprovedBy={setJobApprovedBy} onApprove={() => activeJob && approvalMutation.mutate({ jobId: activeJob.job_id, approvedBy: jobApprovedBy })} onControl={(action) => activeJob && controlMutation.mutate({ jobId: activeJob.job_id, action })} onRetry={() => activeJob && retryMutation.mutate(activeJob.job_id)} onProposalDecision={handleProposalDecision} onProposalReviewLoaded={setActiveProposalReview} onReview={() => activeRun && navigate(runReviewPath(activeRun.run_id))} />
      <RunHistoryPanel runs={runsQuery.data?.runs} pending={runsQuery.isPending} error={runsQuery.error} retry={() => runsQuery.refetch()} />
    </>
  </div>;
}

function HistoricalRunReview({ run, catalog }: { run: RunRecord; catalog: CatalogResponse }) {
  return <div className="page runs-page">
    <PageHeader eyebrow="Run history" title="Canonical run review" description={`${runLabel(run)} · ${sentence(run.mode)} · ${shortId(run.run_id)} · finalized ${formatDate(run.finalized_at ?? run.created_at)}`} actions={<><Link to="/runs"><Button variant="secondary">Back to run workspace</Button></Link><Link to="/compare"><Button>Replay & compare</Button></Link></>} />
    <Callout tone="info" title="Durable historical review">This page was loaded from the canonical run record and can be bookmarked or reopened after a browser reload. Full identifiers and raw metadata remain available in the technical details below.</Callout>
    <RunReview run={run} catalog={catalog} />
  </div>;
}

function RunHistoryPanel({ runs, pending, error, retry }: { runs?: RunRecord[]; pending: boolean; error: unknown; retry: () => void }) {
  const history = runs ?? [];
  return <Panel>
    <PanelHeader eyebrow="Run history" title="Canonical records" detail="Open any completed record in a durable, reload-safe review URL." actions={<Button size="small" variant="ghost" onClick={retry}><RotateCcw/>Refresh</Button>} />
    {pending ? <LoadingState label="Loading canonical run history" /> : error ? <ErrorState title="Run history unavailable" error={error} retry={retry} /> : history.length ? <div className="table-scroll"><table><thead><tr><th>Experiment</th><th>Mode</th><th>Created</th><th>Status</th></tr></thead><tbody>{history.map((run) => <tr key={run.run_id}><td><Link to={runReviewPath(run.run_id)} aria-label={`Review canonical run ${runLabel(run)} (${shortId(run.run_id)})`}><strong>{runLabel(run)}</strong><br/><code title={run.run_id}>{shortId(run.run_id)}</code></Link>{run.is_demo ? <Badge tone="violet">Demo</Badge> : null}</td><td><Badge tone={run.mode === "execute" ? "warning" : "info"}>{sentence(run.mode)}</Badge></td><td>{formatDate(run.created_at)}</td><td><Badge tone={run.status === "completed" ? "success" : "neutral"} dot>{sentence(run.status)}</Badge></td></tr>)}</tbody></table></div> : <div className="inline-empty"><span>No canonical runs yet.</span><span>Complete a Simulate run to create the first durable record.</span></div>}
  </Panel>;
}

function runReviewPath(runId: string) { return `/runs/${encodeURIComponent(runId)}`; }
function runLabel(run: Pick<RunRecord, "objective" | "scenario_id">) { return run.objective ?? run.scenario_id ?? "Completed experiment"; }
function shortId(value: string) { return value.length > 22 ? `${value.slice(0, 10)}…${value.slice(-8)}` : value; }
function cleanupSummary(cleanup: RunRecord["cleanup"]) { if (cleanup === true) return "Reconciled"; if (cleanup === false) return "Outstanding"; if (!cleanup) return "Not recorded"; const status = typeof cleanup.status === "string" ? sentence(cleanup.status) : "Recorded"; const outstanding = typeof cleanup.outstanding_effects === "number" ? ` · ${cleanup.outstanding_effects} outstanding effect${cleanup.outstanding_effects === 1 ? "" : "s"}` : ""; return `${status}${outstanding}`; }

function RunConfigurationPanel({ config, onChange, catalog, preflight }: { config: RunConfiguration; onChange: (config: RunConfiguration) => void; catalog: CatalogResponse; preflight?: PreflightReport }) {
  const set = <K extends keyof RunConfiguration>(key: K, value: RunConfiguration[K]) => onChange({ ...config, [key]: value });
  const profiles = catalog.runner_profiles.filter((profile) => profile.mode === config.mode);
  const selectedProfile = profiles.find((profile) => profile.id === config.profileId);
  const providers = catalog.ai.providers ?? [{ provider_id: catalog.ai.active_provider ?? "deterministic-offline.v1", kind: "deterministic", model: "deterministic-planner.v1", health: { state: catalog.ai.provider_health ?? "not_reported" } }];
  const selectedProvider = providers.find((provider) => provider.provider_id === config.provider) ?? providers[0];
  const providerHealth = selectedProvider?.health?.state ?? catalog.ai.provider_health ?? "not_reported";
  const approvalBinding = preflight?.approval_binding;
  const approvalEnvelope = preflight?.approval_envelope;
  const approvalReviewReady = Boolean(approvalBinding && approvalEnvelope && (preflight?.ready || preflight?.status === "approval_required"));
  return <Panel className="run-config"><PanelHeader eyebrow="Intent" title="Run configuration" detail="Mode, autonomy, provider ID, profile, scope, and registered Execute action selections cross the API boundary. Preflight is authoritative." />
    <div className="config-body">
      <fieldset><legend>Effect mode</legend><div className="choice-grid two">{(["simulate", "execute"] as const).map((mode) => <label key={mode}><input type="radio" name="run-mode" checked={config.mode === mode} onChange={() => onChange({ ...config, mode, profileId: catalog.runner_profiles.find((profile) => profile.mode === mode)?.id ?? "", approved: false, approvedBy: "" })}/><span><strong>{sentence(mode)}</strong><small>{mode === "simulate" ? "Synthetic evidence only" : "Approved runner actions"}</small></span></label>)}</div></fieldset>
      <fieldset><legend>AI autonomy</legend><div className="choice-grid three">{(["off", "assist", "auto"] as AutonomyLevel[]).map((level) => <label key={level}><input type="radio" name="autonomy" checked={config.autonomy === level} onChange={() => set("autonomy", level)}/><span><strong>{sentence(level)}</strong><small>{level === "off" ? "Deterministic" : level === "assist" ? "Review proposal" : "Policy-valid Simulate choices"}</small></span></label>)}</div><p className="field-note">Sent as the canonical off / assist / auto value. Auto may apply only policy-valid Simulate proposals: exact registered next edge, compatible Behavior, typed primitive parameters, exact-profile Action metadata, or one bounded retry. Execute still pauses for review and a fresh one-time approval before any effect.</p></fieldset>
      <details open><summary>Planner & environment</summary><div className="config-grid"><Field label="Provider"><select value={selectedProvider?.provider_id ?? config.provider} onChange={(event) => { const provider = providers.find((item) => item.provider_id === event.target.value); onChange({ ...config, provider: event.target.value, model: provider?.model ?? "", endpoint: "" }); }}>{providers.map((provider) => <option value={provider.provider_id} key={provider.provider_id}>{provider.provider_id}</option>)}</select></Field><Field label="Model" hint="Read from control-plane configuration."><input value={selectedProvider?.model ?? config.model} readOnly disabled/></Field><Field label="Endpoint" hint="Configured server-side; endpoint and credentials are never supplied by this browser."><input value="" placeholder="Control-plane managed" readOnly disabled/></Field><div className="health-field"><span>Provider health</span><Badge tone={providerHealth === "ready" || providerHealth === "healthy" ? "success" : "warning"} dot>{sentence(providerHealth)}</Badge></div><Field label="Runner profile"><select value={config.profileId} onChange={(event) => set("profileId", event.target.value)}><option value="">Select profile</option>{profiles.map((profile) => <option key={profile.id}>{profile.id}</option>)}</select></Field><Field label="Selected runner" hint="The exact active local enrollment is resolved from this profile; manage its lifecycle from Runners."><select disabled value=""><option value="">Resolve authenticated enrollment</option></select></Field><Field label="Target scope" hint="Sent as exact scope references and checked against the selected profile."><input value={config.scopeRefs.join(", ")} onChange={(event) => set("scopeRefs", event.target.value.split(",").map((item) => item.trim()).filter(Boolean))}/></Field><Field label="Safety authority" hint="Derived from the scenario and selected profile; there is no cosmetic override."><input value={selectedProfile?.safety_tiers.map(sentence).join(", ") ?? "Select a profile"} readOnly disabled/></Field></div></details>
      <details id="execute-envelope-review" open={config.mode === "execute" && approvalReviewReady ? true : undefined}><summary>Policy, approval & budgets</summary><Callout title="Profile-owned enforcement">These values come from the selected canonical profile and are bound into preflight. Unsupported browser overrides are intentionally not shown.</Callout><DataList items={[{ label: "Approval", value: selectedProfile ? selectedProfile.approval_required ? "Required for Execute" : "Not required by profile" : "Select a profile" }, { label: "Cleanup", value: selectedProfile ? sentence(selectedProfile.cleanup_policy) : "Select a profile" }, { label: "Maximum steps", value: selectedProfile?.budgets.max_steps ?? "Select a profile" }, { label: "Maximum seconds", value: selectedProfile?.budgets.max_seconds ?? "Select a profile" }, { label: "Maximum artifacts", value: selectedProfile?.budgets.max_artifacts ?? "Select a profile" }, { label: "Maximum bytes", value: selectedProfile?.budgets.max_bytes ? `${Math.round(selectedProfile.budgets.max_bytes / 1_048_576)} MiB` : "Select a profile" }, { label: "Counterfactuals", value: "Planner-derived and always labeled; no unsupported browser switch" }]} />
        {config.mode === "execute" ? <div className="approval-box"><AlertTriangle/><div><strong>Review before durable job creation</strong><p>Review the canonical primary and alternate contracts and acknowledge the exact digests below. This browser acknowledgement is never sent as an execution capability; the durable job requires a new unchecked, job-bound approval after it is created.</p>{approvalReviewReady && approvalBinding && approvalEnvelope ? <div className="approval-binding-summary" aria-label="Execute approval binding"><DataList items={[{ label: "State digest", value: <code>{approvalBinding.state_digest}</code> }, { label: "Plan digest", value: <code>{approvalBinding.plan_digest}</code> }, { label: "Target scope digest", value: <code>{approvalBinding.target_scope_digest}</code> }, { label: "Envelope digest", value: <code>{approvalEnvelope.envelope_digest}</code> }, { label: "Profile / maximum tier", value: `${approvalBinding.profile_id} / ${sentence(approvalBinding.maximum_tier)}` }]} /></div> : <p className="approval-pending">Run preflight first. Job creation stays disabled until the canonical plan, exact scope, and complete approval envelope are displayed.</p>}<label className="check-row"><input type="checkbox" checked={config.approved} disabled={!approvalReviewReady} onChange={(event) => set("approved", event.target.checked)}/><span><strong>I reviewed this exact displayed Execute envelope</strong><small>Local acknowledgement only; cleared after preflight, intent changes, reload, and job submission</small></span></label><Field label="Prepared operator label" hint="Local preparation only. The durable job approval will request identity again."><input value={config.approvedBy} disabled={!approvalReviewReady} onChange={(event) => set("approvedBy", event.target.value)} autoComplete="off" placeholder="Operator label" required={config.mode === "execute"}/></Field></div></div> : null}
      </details>
      <details><summary>Observation & detection</summary><Callout title="Canonical records only">Execute binds selected per-run collectors into preflight and approval. Runner output remains executed evidence; observed records must come from a declared collector. Detection Lab validation is managed separately.</Callout><div className="choice-grid two">{["collector.filesystem.sandbox.v1"].map((collector) => <label key={collector}><input type="checkbox" checked={config.collectors.includes(collector)} disabled/><span><strong>{collector}</strong><small>Required Execute collector for declared sandbox artifacts</small></span></label>)}</div><DataList items={[{ label: "Runner results", value: "Executed evidence, never observed" }, { label: "Independent observation", value: preflight?.collectors?.join(", ") || (config.mode === "execute" ? config.collectors.join(", ") : "Execute only") }, { label: "Unavailable collection", value: "Rejected before Execute or recorded as unknown evidence" }, { label: "Detection lifecycle", value: "Managed in Detection Lab from canonical evidence" }, { label: "Fixture mode", value: "Defined by the chosen scenario, not a browser preference" }]} /></details>
    </div>
  </Panel>;
}

function PlanPreview({ scenarioTitle, stepIds, edgeCount, dirty, config, catalog, preflight }: { scenarioTitle: string; stepIds: string[]; edgeCount: number; dirty: boolean; config: RunConfiguration; catalog: CatalogResponse; preflight?: PreflightReport }) {
  const profile = catalog.runner_profiles.find((item) => item.id === config.profileId); const warnings = [
    ...(config.mode === "execute" && !config.profileId ? ["Execute requires an explicit runner profile."] : []),
    ...(config.mode === "execute" && !config.approved ? ["Execute approval has not been confirmed."] : []),
    ...(config.autonomy === "auto" && catalog.ai.authority === "proposal_only" ? ["Current API reports proposal-only AI authority; Auto will remain bounded by backend capability."] : []),
  ];
  const awaitsExactApproval = preflight?.status === "approval_required" && Boolean(preflight.approval_binding && preflight.approval_envelope);
  const actionOverrideCount = Object.keys(config.actionImplementations).length;
  const nextMove = preflight ? preflight.ready ? "Submit the Simulate job or keep reviewing canonical plan details." : awaitsExactApproval ? "Review the complete Execute envelope, then create the durable approval-gated job." : "Resolve canonical preflight findings before job submission." : dirty ? "Validate and save in Builder when this draft should become reusable; run preflight to test this browser draft." : "Run preflight to bind the current graph, scope, profile, autonomy, and action choices.";
  return <Panel className="plan-preview"><PanelHeader eyebrow="Browser intent" title="Plan preview" detail="Only transmitted intent and selected-profile constraints are shown; canonical preflight below is authoritative." actions={<Badge tone={config.mode === "execute" ? "warning" : "info"}>{config.mode}</Badge>} /><div className="preview-hero"><div><span>Objective</span><strong>{scenarioTitle}</strong><small>{stepIds.length} behaviors · {edgeCount} possible routes</small></div><Gauge/></div><div className="preview-path">{stepIds.map((id, index) => <div key={id}><span>{String(index + 1).padStart(2, "0")}</span><strong>{id}</strong><small>{config.mode === "execute" && config.actionImplementations[id] ? `${config.actionImplementations[id]} · sent for exact binding` : "Control plane resolves implementation"}</small></div>)}</div><DataList items={[{ label: "Autonomy (sent)", value: sentence(config.autonomy) }, { label: "Provider (sent)", value: config.provider }, { label: "Profile (sent)", value: profile?.id ?? "Not selected" }, { label: "Targets (sent)", value: config.scopeRefs.join(", ") || "None" }, { label: "Execute actions (sent)", value: config.mode === "execute" ? Object.entries(config.actionImplementations).map(([step, action]) => `${step}: ${action}`).join(", ") || "Resolve deterministically" : "Omitted for Simulate" }, { label: "Safety tiers (profile)", value: profile?.safety_tiers.map(sentence).join(", ") ?? "Not selected" }, { label: "Cleanup (profile)", value: profile ? sentence(profile.cleanup_policy) : "Not selected" }, { label: "Budget (profile)", value: profile ? `${profile.budgets.max_steps} steps / ${profile.budgets.max_seconds}s / ${Math.round((profile.budgets.max_bytes ?? 0) / 1_048_576)} MiB` : "Not selected" }]} />
    <Callout title="Builder handoff">Run configuration uses the current browser graph exactly as shown. Saving a version makes it reusable, but only preflight can authorize this run intent.</Callout>
    <DataList items={[{ label: "Graph source", value: dirty ? "Unsaved browser draft" : "Saved or packaged graph" }, { label: "Graph shape", value: `${stepIds.length} nodes / ${edgeCount} routes` }, { label: "Action overrides", value: config.mode === "execute" ? `${actionOverrideCount} selected for exact binding` : "Not sent in Simulate" }, { label: "Local Execute review", value: config.mode === "execute" ? config.approved ? "Displayed envelope acknowledged locally" : "Awaiting displayed envelope acknowledgement" : "Not required for Simulate" }, { label: "Preflight state", value: preflight ? sentence(preflight.status) : "Not run for this handoff" }, { label: "Next required move", value: nextMove }]} />
    {warnings.length ? <div className="warning-list">{warnings.map((warning) => <div key={warning}><AlertTriangle/>{warning}</div>)}</div> : <div className="ready-note"><CheckCircle2/> No unresolved browser-side configuration warnings.</div>}
    {preflight ? <div className={`preflight-result ${preflight.ready ? "ready" : awaitsExactApproval ? "approval-required" : "blocked"}`}><header><strong>{preflight.ready ? "Canonical preflight ready" : awaitsExactApproval ? "Canonical envelope awaits confirmation" : "Canonical preflight blocked"}</strong><Badge tone={preflight.ready ? "success" : awaitsExactApproval ? "warning" : "danger"}>{sentence(preflight.status)}</Badge></header><DataList items={[{ label: "Resolved autonomy", value: preflight.autonomy ? sentence(preflight.autonomy) : "Not reported" }, { label: "Resolved profile", value: preflight.runner_profile ?? "None" }, { label: "Scope", value: typeof preflight.scope === "string" ? preflight.scope : JSON.stringify(preflight.scope ?? {}) }, { label: "Safety tier", value: preflight.safety_tier ? sentence(preflight.safety_tier) : "Not reported" }, { label: "Capabilities", value: preflight.capabilities?.join(", ") ?? "Not reported" }, { label: "Approval", value: preflight.approval ?? "Not reported" }, { label: "Cleanup", value: typeof preflight.cleanup === "string" ? preflight.cleanup : JSON.stringify(preflight.cleanup ?? {}) }]} />{preflight.findings?.length ? <ul>{preflight.findings.map((item, index) => <li key={index}>{typeof item === "string" ? item : item.message ?? item.code ?? JSON.stringify(item)}</li>)}</ul> : null}</div> : null}
    {preflight?.plan ? <CanonicalPlanReview plan={preflight.plan} cleanup={preflight.cleanup} scope={preflight.scope} binding={preflight.approval_binding} envelope={preflight.approval_envelope} /> : <Callout title="Canonical plan pending">This browser summary is not an approval envelope. Run preflight to review resolved actions or simulations, parameters, branches, scope, effects, observables, cleanup, and digests.</Callout>}
  </Panel>;
}

function CanonicalPlanReview({ plan, cleanup, scope, binding, envelope }: { plan: Record<string, unknown>; cleanup?: unknown; scope?: unknown; binding?: ApprovalBinding | null; envelope?: ApprovalEnvelope | null }) {
  const steps = Array.isArray(plan.steps) ? plan.steps.filter((item): item is Record<string, unknown> => Boolean(item) && typeof item === "object") : [];
  const edges = Array.isArray(plan.edges) ? plan.edges : [];
  const digest = binding?.plan_digest ?? plan.plan_digest ?? plan.digest ?? plan.scenario_digest;
  return <section className="canonical-plan" aria-label="Canonical preflight plan">
    <header><div><span>{envelope ? "Bound approval envelope" : "Canonical preflight"}</span><strong>Resolved canonical plan</strong></div><Badge tone={envelope ? "warning" : "success"}>{steps.length} resolved steps</Badge></header>
    <DataList items={[{ label: "Plan digest", value: digest ? <code>{String(digest)}</code> : "Not reported" }, { label: "State digest", value: binding ? <code>{binding.state_digest}</code> : "Not required for Simulate" }, { label: "Scope digest", value: binding ? <code>{binding.target_scope_digest}</code> : "Not required for Simulate" }, { label: "Envelope digest", value: envelope ? <code>{envelope.envelope_digest}</code> : "Not required for Simulate" }, { label: "Mode", value: sentence(String(plan.mode ?? "not reported")) }, { label: "Profile / tier", value: binding ? `${binding.profile_id} / ${sentence(binding.maximum_tier)}` : String(plan.runner_profile_id ?? "None") }, { label: "Scope", value: typeof scope === "string" ? scope : JSON.stringify(scope ?? {}) }, { label: "Branches", value: `${edges.length} explicit routes` }, { label: "Cleanup", value: typeof cleanup === "string" ? cleanup : JSON.stringify(cleanup ?? {}) }]} />
    <div className="canonical-steps">{steps.map((step, index) => <article key={String(step.step_id ?? index)}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{String(step.step_id ?? "Unnamed step")}</strong><code>{String(step.behavior_id ?? "Unknown behavior")}</code></div><div><Badge tone={step.action_id ? "warning" : "info"}>{step.action_id ? "Runner action" : "Simulation"}</Badge><code>{String(step.action_id ?? step.simulation_id ?? "Unresolved")}</code></div><dl><div><dt>Parameters</dt><dd><pre>{JSON.stringify(step.parameters ?? {}, null, 2)}</pre></dd></div><div><dt>Inputs</dt><dd><pre>{JSON.stringify(step.inputs ?? {}, null, 2)}</pre></dd></div><div><dt>Expected outputs</dt><dd>{Array.isArray(step.expected_outputs) ? step.expected_outputs.join(", ") || "None" : "Not reported"}</dd></div><div><dt>Required capabilities</dt><dd>{Array.isArray(step.required_capabilities) ? step.required_capabilities.join(", ") || "None" : "Not reported"}</dd></div></dl></article>)}</div>
    {envelope ? <ApprovalEnvelopeReview envelope={envelope} binding={binding} /> : null}
    <details><summary>Raw canonical plan document</summary><pre>{JSON.stringify(plan, null, 2)}</pre></details>
  </section>;
}

function stringList(value: unknown) {
  if (!Array.isArray(value)) return "Not reported";
  return value.map((item) => typeof item === "object" && item !== null ? String((item as Record<string, unknown>).name ?? (item as Record<string, unknown>).id ?? JSON.stringify(item)) : String(item)).join(", ") || "None";
}

function ApprovalEnvelopeReview({ envelope, binding }: { envelope: ApprovalEnvelope; binding?: ApprovalBinding | null }) {
  return <section className="approval-envelope" aria-label="Complete Execute approval envelope">
    <header><div><span>Exact Execute review</span><strong>Primary and alternate behavior contracts</strong><small>{envelope.scenario_id}</small></div><div><Badge tone="warning">{envelope.steps.reduce((count, step) => count + step.options.length, 0)} contract options</Badge><code>{envelope.envelope_digest}</code></div></header>
    {binding ? <p className="envelope-binding-note"><ShieldCheck/>Confirmation binds this envelope to state <code>{binding.state_digest}</code>, plan <code>{binding.plan_digest}</code>, and scope <code>{binding.target_scope_digest}</code>.</p> : null}
    <div className="envelope-steps">{envelope.steps.map((step, stepIndex) => <article key={step.step_id}><header><span>{String(stepIndex + 1).padStart(2, "0")}</span><strong>{step.step_id}</strong><Badge>{step.options.length} option{step.options.length === 1 ? "" : "s"}</Badge></header>{step.options.map((option) => { const contract = option.contract; return <section className="envelope-option" key={`${step.step_id}-${option.behavior_id}`}><header><div><Badge tone={option.is_primary ? "info" : "violet"}>{option.is_primary ? "Primary" : "Auto alternate"}</Badge><strong>{String(contract.title ?? option.behavior_id)}</strong><code>{option.behavior_id}</code></div><code title="Behavior contract digest">{option.contract_digest}</code></header><p>{String(contract.purpose ?? "No behavior purpose was reported.")}</p><dl><div><dt>Resolved parameters</dt><dd><pre>{JSON.stringify(option.resolved_parameters, null, 2)}</pre></dd></div><div><dt>Effects contract</dt><dd>{sentence(String(contract.execution_state ?? "not reported"))} · {sentence(String(contract.safety_tier ?? "not reported"))}</dd></div><div><dt>Expected outputs</dt><dd>{stringList(contract.outputs)}</dd></div><div><dt>Observables</dt><dd>{stringList(contract.telemetry)}{Array.isArray(contract.detection_hints) && contract.detection_hints.length ? ` · Detection hints: ${contract.detection_hints.map(String).join(", ")}` : ""}</dd></div></dl><div className="envelope-actions">{option.actions.length ? option.actions.map((action) => <article key={action.action_id}><header><div><Badge tone={action.contract.mutates ? "warning" : "info"}>{action.contract.mutates ? "Mutating action" : "Non-mutating action"}</Badge><strong>{String(action.contract.title ?? action.action_id)}</strong><code>{action.action_id}</code></div><code title="Action contract digest">{action.contract_digest}</code></header><p>{String(action.contract.purpose ?? "No action purpose was reported.")}</p><DataList items={[{ label: "Capabilities", value: stringList(action.contract.capabilities) }, { label: "Platforms", value: stringList(action.contract.platforms) }, { label: "Effects", value: `${action.contract.mutates ? "Mutates fixture state" : "Read-only"}; ${sentence(String(action.contract.safety_tier ?? "tier not reported"))}` }, { label: "Expected outputs", value: stringList(action.contract.outputs) }, { label: "Cleanup", value: String(action.contract.cleanup_action_id ?? "No cleanup action declared") }]} /><details><summary>Full deterministic action contract</summary><pre>{JSON.stringify(action.contract, null, 2)}</pre></details></article>) : <Callout tone="warning" title="No deterministic action contract">This option cannot authorize runner effects unless the backend resolves an installed action contract.</Callout>}</div><details><summary>Full behavior contract</summary><pre>{JSON.stringify(contract, null, 2)}</pre></details></section>; })}</article>)}</div>
    <details><summary>Raw complete approval envelope</summary><pre>{JSON.stringify(envelope, null, 2)}</pre></details>
  </section>;
}

function normalizeStatus(status: string) { return status === "success" ? "succeeded" : status === "control_blocked" ? "blocked" : status; }
function statusTone(status: string) { const value = normalizeStatus(status); return value === "succeeded" || value === "completed" || value === "cleaned" ? "success" as const : ["blocked", "partial", "awaiting_approval", "paused", "cancelling", "cancelled"].includes(value) ? "warning" as const : ["failed", "refused", "interrupted"].includes(value) ? "danger" as const : value === "counterfactual" ? "violet" as const : "info" as const; }

interface LiveConsoleProps {
  run: RunRecord | null;
  job: RunJob | null;
  events: RunEventPage["items"];
  pending: boolean;
  config: RunConfiguration;
  approvalPreflight?: PreflightReport;
  approvalRequest: Record<string, unknown> | null;
  proposalReview?: AIProposalReview;
  approvalConfirmed: boolean;
  approvedBy: string;
  approvalPending: boolean;
  controlPending: boolean;
  onApprovalConfirmed: (confirmed: boolean) => void;
  onApprovedBy: (identity: string) => void;
  onApprove: () => void;
  onControl: (action: "pause" | "resume" | "cancel") => void;
  onRetry: () => void;
  onProposalDecision: (result: AIProposalDecisionResult, review: AIProposalReview) => void;
  onProposalReviewLoaded: (review: AIProposalReview) => void;
  onReview: () => void;
}

function LiveConsole({ run, job, events, pending, config, approvalPreflight, approvalRequest, proposalReview, approvalConfirmed, approvedBy, approvalPending, controlPending, onApprovalConfirmed, onApprovedBy, onApprove, onControl, onRetry, onProposalDecision, onProposalReviewLoaded, onReview }: LiveConsoleProps) {
  const [tab, setTab] = useState<"timeline" | "planner" | "policy" | "runner" | "evidence" | "detections">("timeline");
  const previewSteps: RunStep[] = pending ? [{ step_id: "durable_job", status: job?.state ?? "planning", execution_disposition: job?.state === "awaiting_approval" ? "callback_not_started" : config.mode === "simulate" ? "simulation_job" : "approval_gated_job" }] : [];
  const steps = run?.steps ?? previewSteps;
  const canPause = job?.state === "running";
  const canResume = job?.state === "paused";
  const canCancel = Boolean(job && !terminalJobStates.has(job.state));
  return <Panel className="live-console"><PanelHeader eyebrow="Live orchestration" title={run ? run.run_id : job ? job.job_id : pending ? "Job submission in progress" : "No active job"} detail={run ? `${sentence(run.mode)} · ${sentence(run.status)} · ${run.is_demo ? "sanitized demo" : "canonical local record"}` : job ? `${sentence(job.kind)} · durable ${sentence(job.state)} state · ${events.length} incremental events · updated ${formatDate(job.updated_at)}` : "Complete preflight, then submit a durable local job."} actions={<div className="run-controls"><Button size="small" variant="ghost" disabled={!canPause || controlPending} onClick={() => onControl("pause")} title={canPause ? "Pause at the next cooperative checkpoint" : "Pause is available only while running"}><Pause/>Pause</Button><Button size="small" variant="ghost" disabled={!canResume || controlPending} onClick={() => onControl("resume")} title={canResume ? "Resume the cooperatively paused job" : "Resume is available only while paused"}><RotateCcw/>Resume</Button>{job?.state === "interrupted" ? <Button size="small" variant="secondary" disabled={controlPending} onClick={onRetry} title="Create a replacement job with fresh preflight and approval"><RotateCcw/>Retry as replacement</Button> : null}<Button size="small" variant="danger" disabled={!canCancel || controlPending} onClick={() => onControl("cancel")} title={canCancel ? "Request cooperative cancellation" : "This job is terminal"}><CircleStop/>Cancel</Button>{run ? <Button size="small" onClick={onReview}><FileSearch/>Review</Button> : null}</div>} />
    {DEMO_MODE ? <div className="console-banner"><Sparkles/>Demo lifecycle states are presentation fixtures only. No runner was dispatched.</div> : null}
    {job?.state === "awaiting_approval" && job.progress.approval_kind !== "ai_proposal" ? <JobApprovalGate job={job} preflight={approvalPreflight} approvalRequest={approvalRequest} proposalReview={proposalReview} confirmed={approvalConfirmed} approvedBy={approvedBy} pending={approvalPending} onConfirmed={onApprovalConfirmed} onApprovedBy={onApprovedBy} onApprove={onApprove} /> : null}
    {job && typeof job.progress.proposal_record_id === "string" ? <ProposalReviewWorkspace job={job} onDecision={onProposalDecision} onReviewLoaded={onProposalReviewLoaded}/> : null}
    {job?.error ? <Callout tone="danger" title={job.error.code ?? "Job failed"}>{job.error.message ?? "The durable job ended with a sanitized error record."}</Callout> : null}
    <div className="live-path">{steps.length ? steps.map((step, index) => <article key={`${step.step_id}-${index}`} data-status={normalizeStatus(step.status)}><header><span>{String(index + 1).padStart(2, "0")}</span><Badge tone={statusTone(step.status)} dot>{sentence(normalizeStatus(step.status))}</Badge></header><strong>{step.step_id}</strong><small>{step.action_id ?? step.simulation_id ?? sentence(step.execution_disposition ?? "pending")}</small></article>) : <div className="console-empty"><Activity/><strong>Awaiting a run</strong><span>Planner, policy, dispatch, evidence, detection, and cleanup events will remain separate.</span></div>}</div>
    <div className="console-tabs" role="tablist" aria-label="Run detail views">{(["timeline", "planner", "policy", "runner", "evidence", "detections"] as const).map((item) => <button key={item} role="tab" aria-selected={tab === item} onClick={() => setTab(item)}>{sentence(item)}</button>)}</div>
    <div className="console-detail">{tab === "timeline" ? <Timeline run={run} job={job} events={events} pending={pending} /> : tab === "planner" ? <StructuredPanel value={run?.planner_decisions?.length ? run.planner_decisions : run?.plan} empty="No planner decisions are available." /> : tab === "policy" ? <StructuredPanel value={run?.policy} empty="No policy decisions are available." /> : tab === "runner" ? <RunnerDetail run={run} /> : tab === "evidence" ? <EvidenceDetail run={run} /> : <DetectionDetail run={run} />}</div>
  </Panel>;
}

function JobApprovalGate({ job, preflight, approvalRequest, proposalReview, confirmed, approvedBy, pending, onConfirmed, onApprovedBy, onApprove }: { job: RunJob; preflight?: PreflightReport; approvalRequest: Record<string, unknown> | null; proposalReview?: AIProposalReview; confirmed: boolean; approvedBy: string; pending: boolean; onConfirmed: (confirmed: boolean) => void; onApprovedBy: (identity: string) => void; onApprove: () => void }) {
  const binding = preflight?.approval_binding;
  const envelope = preflight?.approval_envelope;
  const proposalExecute = job.progress.approval_kind === "ai_proposal_execute";
  const resolutionRecord = proposalReview?.resolution && typeof proposalReview.resolution === "object" ? proposalReview.resolution : undefined;
  const continuation = resolutionRecord?.continuation;
  const continuationRecord = continuation && typeof continuation === "object" ? continuation as Record<string, unknown> : undefined;
  const approvalRequestId = typeof approvalRequest?.approval_id === "string" ? approvalRequest.approval_id : undefined;
  const progressApprovalRequestId = typeof job.progress.approval_request_id === "string" ? job.progress.approval_request_id : undefined;
  const originalApprovalRequestId = typeof job.request?.approval_request_id === "string" ? job.request.approval_request_id : undefined;
  const ordinaryRequestReady = Boolean(approvalRequestId && originalApprovalRequestId === approvalRequestId && (progressApprovalRequestId === undefined || progressApprovalRequestId === approvalRequestId));
  const proposalRequestReady = Boolean(approvalRequestId && progressApprovalRequestId === approvalRequestId && originalApprovalRequestId && originalApprovalRequestId !== approvalRequestId && resolutionRecord?.approval_request_id === approvalRequestId);
  const pendingRequestReady = approvalRequest?.status === "pending" && (proposalExecute ? proposalRequestReady : ordinaryRequestReady);
  const exactBindingMatches = Boolean(binding && approvalBindingFields.every((field) => typeof approvalRequest?.[field] === "string" && approvalRequest[field] === binding[field]));
  const freshBindingReady = pendingRequestReady && approvalBindingFields.every((field) => typeof approvalRequest?.[field] === "string") && proposalReview?.status === "accepted" && Boolean(continuationRecord?.execute_approval_binding_digest);
  const exactEnvelopeReady = proposalExecute ? freshBindingReady : Boolean(preflight?.plan && binding && envelope && pendingRequestReady && exactBindingMatches);
  return <section className="job-approval-gate" id="durable-execute-approval" aria-label="Durable Execute job approval">
    <header><div><AlertTriangle/><span><strong>{proposalExecute ? "Fresh Execute approval after proposal acceptance" : "Explicit one-time Execute approval"}</strong><small>The execution callback has not started. Proposal acceptance and effect authorization are separate decisions.</small></span></div><Badge tone="warning" dot>Awaiting approval</Badge></header>
    <DataList items={[{ label: "Durable job", value: <code>{job.job_id}</code> }, { label: "Approval request", value: <code>{String(approvalRequest?.approval_id ?? "Not reported")}</code> }, { label: "Expires", value: formatDate(typeof approvalRequest?.expires_at === "string" ? approvalRequest.expires_at : undefined) }, { label: "Profile / tier", value: proposalExecute ? `${String(approvalRequest?.profile_id ?? "Not reported")} / ${sentence(String(approvalRequest?.maximum_tier ?? "not reported"))}` : binding ? `${binding.profile_id} / ${sentence(binding.maximum_tier)}` : "Not reported" }, { label: "State digest", value: <code>{String(proposalExecute ? approvalRequest?.state_digest ?? "Not reported" : binding?.state_digest ?? "Not reported")}</code> }, { label: "Plan digest", value: <code>{String(proposalExecute ? approvalRequest?.plan_digest ?? "Not reported" : binding?.plan_digest ?? "Not reported")}</code> }, { label: "Scope digest", value: <code>{String(proposalExecute ? approvalRequest?.target_scope_digest ?? "Not reported" : binding?.target_scope_digest ?? "Not reported")}</code> }, { label: proposalExecute ? "Continuation binding digest" : "Envelope digest", value: <code>{String(proposalExecute ? continuationRecord?.execute_approval_binding_digest ?? "Not reported" : envelope?.envelope_digest ?? "Not reported")}</code> }]} />
    {!pendingRequestReady ? <Callout tone="danger" title="Pending approval binding unavailable">Approval remains disabled until this job reports the same pending approval request ID returned with its immutable envelope.</Callout> : null}
    {proposalExecute ? proposalReview && continuationRecord ? <><Callout tone="warning" title="Fresh envelope, original approval refused">The accepted registered behavior is recompiled into a lineage-linked continuation. This fresh request is bound to the mutated scenario, resume point, exact scope, profile, tier, provider, and proposal lineage.</Callout><DataList items={[{ label: "Proposal record", value: <code>{proposalReview.proposal_record_id}</code> }, { label: "Selected behavior", value: <code>{String(continuationRecord.selected_behavior_id ?? proposalReview.record.proposal?.selected_behavior_id ?? "Not reported")}</code> }, { label: "Resume step", value: <code>{String(continuationRecord.resume_from_step_id ?? "Not reported")}</code> }, { label: "Continuation plan digest", value: <code>{String(continuationRecord.continuation_plan_digest ?? "Not reported")}</code> }, { label: "Proposal digest", value: <code>{proposalReview.proposal_digest}</code> }]} /></> : <Callout tone="danger" title="Fresh proposal envelope unavailable">Approval remains disabled until the accepted proposal detail and fresh binding are loaded.</Callout> : preflight?.plan ? <><CanonicalPlanReview plan={preflight.plan} cleanup={preflight.cleanup} scope={preflight.scope} binding={binding} envelope={envelope} />{binding && !exactBindingMatches ? <Callout tone="danger" title="Approval envelope mismatch">Approval remains disabled because the server-returned request does not exactly match all five preflight binding fields.</Callout> : null}</> : <Callout tone="danger" title="Exact review unavailable">Approval remains disabled because the job submission did not return its canonical preflight plan.</Callout>}
    <div className="job-approval-controls"><label className="check-row"><input type="checkbox" checked={confirmed} disabled={!exactEnvelopeReady || pending} onChange={(event) => onConfirmed(event.target.checked)}/><span><strong>I approve this exact immutable {proposalExecute ? "proposal continuation" : "job envelope"} once</strong><small>Unchecked by default and never stored in browser persistence</small></span></label><Field label="Operator identity for this job"><input value={approvedBy} disabled={!exactEnvelopeReady || pending} onChange={(event) => onApprovedBy(event.target.value)} autoComplete="off" placeholder="Operator label"/></Field><Button variant="primary" disabled={!exactEnvelopeReady || !confirmed || !approvedBy.trim() || pending} onClick={onApprove}>{pending ? <Activity className="spin"/> : <ShieldCheck/>}{pending ? "Applying one-time approval" : "Approve and release job"}</Button><p>The server recomputes the binding, validates the pending capability, consumes it atomically, then releases only this job. Changing configuration elsewhere cannot alter this immutable request.</p></div>
  </section>;
}

function Timeline({ run, job, events: incrementalEvents, pending }: { run: RunRecord | null; job: RunJob | null; events: RunEventPage["items"]; pending: boolean }) {
  const events = incrementalEvents.length ? incrementalEvents : run?.events?.length ? run.events : run?.steps.map((step, index) => ({ type: normalizeStatus(step.status), step_id: step.step_id, sequence: index + 1, disposition: step.execution_disposition })) ?? (job ? [{ type: job.state, sequence: 1, disposition: job.state === "awaiting_approval" ? "Execution callback has not started" : `Durable job phase ${String(job.progress.phase ?? job.state)}`, timestamp: job.updated_at }] : []);
  if (!events.length && !pending) return <div className="console-empty compact"><Clock3/><span>No audit events are available.</span></div>;
  return <ol className="timeline">{pending && !events.length ? <li><span className="timeline-dot planning"/><div><strong>Planning request submitted</strong><p>The browser is awaiting a canonical control-plane response; it is not inventing progress.</p></div><time>Now</time></li> : events.map((event: any, index) => <li key={Number(event.sequence ?? index + 1)}><span className={`timeline-dot ${normalizeStatus(String(event.type ?? event.event_type ?? event.status ?? "observed"))}`}/><div><strong>{sentence(String(event.type ?? event.event_type ?? event.status ?? "event"))}</strong><p>{event.step_id ? `${event.step_id} · ` : ""}{sentence(String(event.disposition ?? event.message ?? "Canonical record"))}</p></div><time>{event.timestamp ? formatDate(event.timestamp) : `#${event.sequence ?? index + 1}`}</time></li>)}</ol>;
}

function StructuredPanel({ value, empty }: { value: unknown; empty: string }) {
  if (value === null || value === undefined || (Array.isArray(value) && !value.length)) return <div className="console-empty compact"><ListTree/><span>{empty}</span></div>;
  const entries = Array.isArray(value) ? value.map((item, index) => [`Record ${index + 1}`, item] as const) : typeof value === "object" ? Object.entries(value as Record<string, unknown>) : [["Value", value] as const];
  return <div className="structured-list">{entries.map(([key, item]) => <article key={key}><strong>{sentence(key)}</strong>{typeof item === "object" ? <pre>{JSON.stringify(item, null, 2)}</pre> : <span>{String(item)}</span>}</article>)}</div>;
}

function RunnerDetail({ run }: { run: RunRecord | null }) {
  if (!run) return <div className="console-empty compact"><TerminalSquare/><span>No runner dispatch records are available.</span></div>;
  const executed = run.steps.filter((step) => step.action_id); return <div>{executed.length ? <div className="structured-list">{executed.map((step) => <article key={step.step_id}><strong>{step.step_id}</strong><code>{step.action_id}</code><span>{sentence(step.status)}</span></article>)}</div> : <Callout title="No runner dispatch reported">This run used simulation adapters or lacks runner records. Simulation is not execution.</Callout>}</div>;
}

export function EvidenceDetail({ run }: { run: RunRecord | null }) {
  const records = run?.evidence?.records ?? []; if (!records.length) return <div className="console-empty compact"><FileSearch/><span>No evidence records are available.</span></div>;
  return <div className="record-grid">{records.map((record, index) => { const content = record.content ?? record.fields; const contentSummary = content && typeof content.summary === "string" ? content.summary : undefined; return <article key={record.evidence_id ?? record.id ?? index}><header><Badge tone={record.provenance === "observed" ? "success" : record.provenance === "control_blocked" ? "warning" : record.provenance === "counterfactual" ? "violet" : "info"}>{sentence(record.provenance)}</Badge><code>{record.step_id ?? "unattributed"}</code></header><strong>{record.kind ?? record.behavior_id ?? "Evidence record"}</strong><p>{record.summary ?? contentSummary ?? "Canonical structured evidence content."}</p><div className="evidence-meta"><span>Producer <code>{record.producer ?? "Not reported"}</code></span><span>Behavior <code>{record.behavior_id ?? "Not reported"}</code></span><span>Action <code>{record.action_id ?? "None"}</code></span><span>Confidence {typeof record.confidence === "number" ? `${Math.round(record.confidence * 100)}%` : "Not reported"}</span></div>{content ? <details><summary>Show technical evidence content</summary><pre aria-label={`Evidence content ${record.evidence_id ?? record.id ?? index + 1}`}>{JSON.stringify(content, null, 2)}</pre></details> : null}{record.limitations?.length ? <div className="evidence-limitations"><strong>Limitations</strong><ul>{record.limitations.map((item) => <li key={item}>{item}</li>)}</ul></div> : null}</article>; })}</div>;
}

export function DetectionDetail({ run }: { run: RunRecord | null }) {
  const candidates = run?.detections?.candidates ?? []; if (!candidates.length) return <div className="console-empty compact"><FileSearch/><span>No detection candidates are linked to this run.</span></div>;
  return <div className="record-grid">{candidates.map((item, index) => <article key={item.candidate_id ?? item.id ?? index}><header><Badge tone={item.state === "rejected" ? "danger" : item.state.includes("exercised") || item.state === "benign_evaluated" ? "success" : "info"}>{sentence(item.state)}</Badge><code>{item.target_language ?? item.language ?? "query"}</code></header><strong>{item.title ?? item.candidate_id ?? "Detection candidate"}</strong><p>{item.summary ?? "Lifecycle state reflects only completed validation stages."}</p></article>)}</div>;
}

export function RunReview({ run, catalog }: { run: RunRecord; catalog: CatalogResponse }) {
  const firstBlocked = run.steps.find((step) => ["blocked", "control_blocked", "refused"].includes(step.status)); const evidence = run.evidence?.records ?? []; const detections = run.detections?.candidates ?? [];
  const aiProposals = Array.isArray(run.ai_proposals) ? run.ai_proposals : [];
  const provenance = Object.fromEntries([...new Set(evidence.map((item) => item.provenance))].map((kind) => [kind, evidence.filter((item) => item.provenance === kind).length]));
  return <div className="review-stack">{run.is_demo ? <Callout title="Seeded review">This is a sanitized Simulate record. It does not prove runner execution, independent observation, or a real control block.</Callout> : null}{run.approval_pause ? <Callout tone="warning" title="Planner stopped before the next action">A review-required proposal paused before the selected node. Its durable job—not this immutable run record—owns the exact-digest accept/reject gate; accepting Execute still requires a new one-time approval.</Callout> : null}<div className="stat-grid"><Stat label="Objective" value={run.objective_reached ? "Reached" : "Prevented / incomplete"} tone={run.objective_reached ? "success" : "warning"}/><Stat label="Path" value={`${run.steps.length} nodes`} detail={`${run.steps.filter((step) => step.action_id).length} runner actions`}/><Stat label="Evidence" value={evidence.length} detail={Object.entries(provenance).map(([key, value]) => `${key}: ${value}`).join(" · ") || "None"}/><Stat label="Detections" value={detections.length} detail={detections.map((item) => sentence(item.state)).join(" · ") || "None"}/></div>
    <div className="review-grid"><Panel><PanelHeader eyebrow="Executive summary" title={run.objective ?? run.scenario_id ?? "Completed experiment"}/><div className="review-summary"><Badge tone={statusTone(run.status)} dot>{sentence(run.status)}</Badge><p>{run.objective_reached ? "The recorded path reached its declared objective within the selected policy envelope." : firstBlocked ? `The recorded path did not reach its objective. The first prevention or refusal point was ${firstBlocked.step_id}.` : "The objective was not recorded as reached; inspect limitations and evidence before drawing a conclusion."}</p><DataList items={[{ label: "Run ID", value: <code title={run.run_id}>{shortId(run.run_id)}</code> }, { label: "Mode", value: sentence(run.mode) }, { label: "Autonomy", value: sentence(run.autonomy ?? run.autonomy_level ?? (run.ai_enabled ? "assist" : "off")) }, { label: "Profile", value: run.runner_profile_id ?? "Not recorded" }, { label: "Started", value: formatDate(run.created_at) }, { label: "Finalized", value: formatDate(run.finalized_at) }]} /></div></Panel><Panel><PanelHeader eyebrow="First prevention" title={firstBlocked ? firstBlocked.step_id : "No block recorded"}/>{firstBlocked ? <Callout tone="warning" title={sentence(firstBlocked.status)}>{firstBlocked.execution_disposition ? sentence(firstBlocked.execution_disposition) : "Inspect policy and independently observed evidence before attributing the cause."}</Callout> : <Callout tone="success" title="Path completed without a recorded block">Absence of a block is not proof that every defensive control observed the behavior.</Callout>}<DataList items={[{ label: "Cleanup", value: cleanupSummary(run.cleanup) }, { label: "Manifest", value: run.manifest ? "Canonical file table available" : "Not attached" }, { label: "Replay lineage", value: run.replay ? "Replay-linked" : "Original run" }]} /></Panel></div>
    <Panel><PanelHeader eyebrow="Path taken" title="Behavior and execution outcomes"/><div className="review-path">{run.steps.map((step, index) => { const behavior = catalog.behaviors.find((item) => item.id === step.behavior_id); return <article key={`${step.step_id}-${index}`}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{behavior?.title ?? step.step_id}</strong><code>{step.step_id}</code></div><div><Badge tone={statusTone(step.status)}>{sentence(normalizeStatus(step.status))}</Badge><small>{step.action_id ? `Action ${step.action_id}` : step.simulation_id ? `Simulation ${step.simulation_id}` : sentence(step.execution_disposition ?? "unknown")}</small></div></article>; })}</div></Panel>
    <AIProposalTrail proposals={aiProposals} />
    <div className="two-column"><Panel><PanelHeader eyebrow="Evidence graph" title="Provenance-separated records"/><EvidenceDetail run={run}/></Panel><Panel><PanelHeader eyebrow="Detection outcome" title="Candidate lifecycle"/><DetectionDetail run={run}/></Panel></div>
    <Panel><PanelHeader eyebrow="Reproducibility" title="Limitations and technical metadata"/><div><h3>Limitations</h3>{run.limitations?.length ? <ul>{run.limitations.map((item) => <li key={item}>{item}</li>)}</ul> : <p>No limitations were attached. Treat missing limitations as incomplete metadata.</p>}<details><summary>Show raw reproducibility metadata</summary><div className="raw-columns"><StructuredPanel value={run.manifest ?? { schema_version: run.schema_version, scenario_id: run.scenario_id, profile_id: run.runner_profile_id }} empty="No manifest metadata."/><pre aria-label="Canonical run technical record">{JSON.stringify({ run_id: run.run_id, schema_version: run.schema_version, scenario_id: run.scenario_id, runner_profile_id: run.runner_profile_id, cleanup: run.cleanup ?? null, replay: run.replay ?? null }, null, 2)}</pre></div></details></div></Panel>
  </div>;
}

function AIProposalTrail({ proposals }: { proposals: NonNullable<RunRecord["ai_proposals"]> }) {
  if (!proposals.length) return <Panel><PanelHeader eyebrow="AI Auto journey" title="No runtime AI proposals"/><Callout title="Deterministic path">This run did not retain any Assist or Auto proposal records; planner decisions remained deterministic.</Callout></Panel>;
  return <Panel><PanelHeader eyebrow="AI Auto journey" title="Proposal, policy, and application trail" detail="Completed records show exactly what the provider proposed and what deterministic policy permitted, reviewed, or refused." actions={<Badge tone="violet">{proposals.length} proposal{proposals.length === 1 ? "" : "s"}</Badge>}/>
    <div className="record-grid">{proposals.map((record, index) => {
      const proposal = record.proposal ?? undefined;
      const provider = record.provider ?? {};
      const policy = record.proposal_policy_evaluation ?? {};
      return <article key={String(record.proposal_record_id ?? proposal?.proposal_id ?? index)}><header><Badge tone={String(record.application_status ?? "").startsWith("applied") || String(record.application_status ?? "").startsWith("accepted") ? "success" : String(record.application_status ?? "").includes("approval") ? "warning" : "info"}>{sentence(String(record.application_status ?? "recorded"))}</Badge><code>{String(proposal?.proposal_id ?? record.proposal_record_id ?? `proposal-${index + 1}`)}</code></header><strong>{sentence(String(proposal?.proposal_type ?? "proposal"))}</strong><p>{proposal?.rationale ?? "No provider rationale was retained."}</p><DataList items={[{ label: "Provider", value: `${String(provider.effective_provider_id ?? provider.requested_provider_id ?? "Not reported")}${provider.used_fallback ? ` · fallback: ${sentence(String(provider.fallback_reason ?? "used"))}` : ""}` }, { label: "Selected step", value: proposal?.selected_step_id ? <code>{proposal.selected_step_id}</code> : "None" }, { label: "Selected Behavior", value: proposal?.selected_behavior_id ? <code>{proposal.selected_behavior_id}</code> : "None" }, { label: "Selected Action", value: proposal?.selected_action_id ? <code>{proposal.selected_action_id}</code> : "None" }, { label: "Observed outcome", value: sentence(String(record.outcome ?? proposal?.selected_edge?.outcome ?? "not reported")) }, { label: "Policy", value: sentence(String(policy.status ?? "not reported")) }]} />{proposal?.selected_edge ? <p className="field-note">Exact registered edge: <code>{proposal.selected_edge.from_step} / {proposal.selected_edge.outcome} / {proposal.selected_edge.to_step}</code></p> : null}{proposal?.parameter_changes?.length ? <details><summary>Typed primitive parameter changes</summary><pre>{JSON.stringify(proposal.parameter_changes, null, 2)}</pre></details> : null}</article>;
    })}</div>
    <Callout title="Model output stayed proposal-only">Auto can apply only policy-valid Simulate choices from registered Behavior/Action contracts; Execute proposals still require durable review plus a fresh one-time approval before runner effects.</Callout>
  </Panel>;
}
