"""Generate Sigma detection drafts from module outputs."""

from __future__ import annotations

from typing import Any, Dict


def _safe(value: str) -> str:
    return (
        value.lower()
        .replace(" ", "-")
        .replace("/", "-")
        .replace(":", "-")
        .replace("_", "-")
    )


def generate_sigma_rule(hint: Dict[str, Any]) -> str:
    """Render a Sigma rule document as YAML text."""
    title = str(hint.get("title", "BlueFire Detection"))
    technique = str(hint.get("mitre_technique", hint.get("mitre_technique_id", "T0000")))
    logsource = hint.get("logsource", {"category": "process_creation", "product": "windows"})
    detection = hint.get(
        "detection",
        {"selection": {"event.provider": "bluefire"}, "condition": "selection"},
    )
    rule_id = _safe(f"bluefire-{title}-{technique}")[:64]
    return "\n".join(
        [
            f"title: {title}",
            f"id: {rule_id}",
            "status: experimental",
            "description: Auto-generated by BlueFire-Nexus detection engine",
            "logsource:",
            f"  category: {logsource.get('category', 'process_creation')}",
            f"  product: {logsource.get('product', 'windows')}",
            "detection:",
            "  selection:",
            *[
                f"    {key}: {value}"
                for key, value in (detection.get("selection") or {}).items()
            ],
            f"  condition: {detection.get('condition', 'selection')}",
            "tags:",
            f"  - attack.{technique.lower()}",
            "level: medium",
            "",
        ]
    )


def build_sigma_rule(run_id: str, module: str, hint: Dict[str, Any]) -> Dict[str, Any]:
    """Compatibility helper used by detection engine."""
    title = str(hint.get("title", f"BlueFire {module} activity ({run_id})"))
    technique = str(hint.get("mitre_technique", hint.get("mitre_technique_id", "T0000")))
    detection = hint.get(
        "detection",
        {"selection": {"module": module, "run_id": run_id}, "condition": "selection"},
    )
    return {
        "title": title,
        "id": _safe(f"{module}-{run_id}-{technique}")[:64],
        "status": "experimental",
        "description": "Auto-generated by BlueFire-Nexus detection engine",
        "logsource": hint.get("logsource", {"category": "process_creation", "product": "windows"}),
        "detection": detection,
        "fields": ["CommandLine", "ParentCommandLine", "Image"],
        "tags": [f"attack.{technique.lower()}"],
        "level": "medium",
    }
